<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt" style="margin-top: 2px !important;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-book"></i>&nbsp;<label class="title">QUESTIONÁRIOS DE APRENDIZAGEM</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 10px;padding-right: 10px;margin-top: 10px;margin-bottom: 20px;">
                                            <form action="/usuarios/membros" method="post" enctype="">
                                                <div class="col-md-offset-10 col-md-2 col-sm-12 col-xs-6">
                                                    <button class="btn btn-primary-borded2 form-control" type="button" onClick="showAdd()">
                                                        Novo&nbsp;
                                                        <i class="fa fa-plus"></i>
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="table-responsive" style="margin-top: 10px;">
                                            <?php
                                            $relatorio->gerarCabecalho(12);
                                            if ($questionarios) {
                                                foreach ($questionarios as $dados) {
                                                    
                                                    $relatorio->definirVariavel('1', "<a href='/questionario/aprendizagem/".$dados['cod_questionario']."' class='btn btn-primary4' style='width:100%;margin-bottom:2px'><i class='pointer fa fa-sign-in'></i></a>");
                                                    
                                                    if($dados['is_my'] == "1"){
                                                        
                                                        if($dados['status_questionario'] == "0"){
                                                            $relatorio->definirVariavel('0', '<div class="switch_box box_1"><input type="checkbox" class="switch_1 ativar-chbox" id="alterar_status" questionario="'.$dados['cod_questionario'].'" name="alterar_status"></div>');
                                                        }else{
                                                            $relatorio->definirVariavel('0', '<div class="switch_box box_1"><input type="checkbox" class="switch_1 ativar-chbox" id="alterar_status" questionario="'.$dados['cod_questionario'].'" name="alterar_status" checked></div>');    
                                                        }
                                                        
                                                        $relatorio->definirVariavel('2', "<a type='button' class='btn btn-primary4' style='width:100%;margin-bottom:2px' onClick=showEdit('".$dados['cod_questionario']."','1')><i class='pointer fa fa-pencil'></i></button>");
                                                        $relatorio->definirVariavel('3', "<a type='button' class='btn btn-primary4' style='width:100%;margin-bottom:2px' onClick=showDelete('".$dados['cod_questionario']."','1')><i class='pointer fa fa-times'></i></button>");
                                                    }else{
                                                        $relatorio->definirVariavel('0', "");
                                                        $relatorio->definirVariavel('2', "");
                                                        $relatorio->definirVariavel('3', "");
                                                    }
                                                    
                                                    $relatorio->definirVariavel('4', "<a href='/questionario/resultado/".$dados['cod_questionario']."' class='btn btn-primary4' style='width:100%;margin-bottom:2px'><i class='pointer fa fa-file-text'></i></a>");
                                                    
                                                    $relatorio->gerarRelatorio($dados);
                                                }
                                            }
                                            $relatorio->gerarRodape();
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalAdd" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document" style="max-width: 1300px !important;">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title color-primary2"><i class="fa fa-plus"></i>&nbsp;Adicionar novo Questionário</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="info_quest">
                    <form>
                        <div class="form-group">
                            <label for="add_desc" class="col-form-label">Descrição sobre o Questionário: <label style="color:red">*</label></label>
                            <input type="text" class="form-control" id="add_desc">
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type='button' class='btn btn-primary-borded2' onclick="addQuestionario()" style='margin-bottom:2px'>Adicionar <i class="fa fa-plus"></i></button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalEdit" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document" style="max-width: 1300px !important;">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title color-primary2"><i class="fa fa-pencil"></i>&nbsp;Editar Questionário</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="info_quest">
                    <form>
                        <div class="form-group">
                            <label for="edit_desc" class="col-form-label">Descrição sobre o Questionário: <label style="color:red">*</label></label>
                            <input type="text" class="form-control" id="edit_desc">
                            <input type="hidden" class="form-control" id="cod_questionario">
                            <input type="hidden" class="form-control" id="tipo_questionario">
                        </div>
                        <div class="text-right">
                            <button type="button" disabled="true" class="btn btn-primary3" id="edit_questionario_desc" onclick="editQuestionar();">Salvar descrição&nbsp;<i class="fa fa-save"></i></button>
                        </div>
                    </form>
                </div>
                <div id="pergunta_quest">
                    <hr>
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-4 col-md-4">
                                <div class="panel-group" id="accordion">
                                    <div class="panel-default">
                                        <div class="panel-heading back-primary3">
                                            <h4 class="panel-title">
                                                Questões
                                            </h4>
                                        </div>
                                        <div id="collapseFour" class="panel panel-collapse">
                                            <a href="#" onclick="addQuestao(2);" class="list-group-item text-center pointer">
                                                <i class="fa fa-plus"></i>&nbsp;Adicionar Questão
                                            </a>
                                            <div id="perguntas_edit">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-8 col-md-8">
                                <?php echo $this->partial('partials/questionario/nova-questao');?>
                                <?php echo $this->partial('partials/questionario/edit-questao');?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>





<script type="text/javascript">

    $(document).ready(function () {
        $('#relatorio').DataTable({
            "language": {
                "url": "/js/datatable/pt-br.json"
            },
            "ordering": false,
            "columnDefs": [ {"orderable": false} ],
            "lengthChange": false,
            "searching": false
        });
        
    });
    
    function proximo(){
        
        if($('#add_desc').val()){
            $('#add_desc').attr('readonly',true);
        }else{
            Swal.fire({
                title: 'Atenção!',
                html: 'Digite a descrição sobre o Questionário.',
                type: 'info'
            });
        }
    }
    
    $('#edit_desc').on('keydown', function(){
        $('#edit_questionario_desc').attr('disabled', false);
    });
    
    $('.ativar-chbox').on('change', function(){
        
        var element = $(this);
        
        var ativar = $(this).is(':checked') ? 1 : 0;
        
        var questionario = $(this).attr('questionario');
        
        $.ajax({
            url: '/questionario/cadastro/ativarQuestionario',
            data: {
                questionario      : questionario,
                tipo              : 2,
                ativar            : ativar
            },
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = JSON.parse(retorno);
                Swal.close();
                if(!retorno.response){
                    Swal.fire({
                        title: 'Atenção!',
                        html: retorno.msg,
                        type: 'info',
                        onClose: () => {
                            $(element).prop('checked',false);
                        }
                    });
                }
            }
        });
        /*
        if(ativar == 1){
            $(this).attr('checked', true);
        }else{
            $(this).attr('checked', false);
        }
        */
    });
    
    function addQuestionario(){
        if($('#add_desc').val()){
            $('#add_desc').attr('readonly',true);
        }else{
            Swal.fire({
                title: 'Atenção!',
                html: 'Digite a descrição sobre o Questionário.',
                type: 'info'
            });
        }
        
        $.ajax({
            url: '/questionario/cadastro/novoQuestionario',
            data: {
                descricao : $('#add_desc').val(),
                tipo      : 2
            },
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                Swal.fire({
                    title: 'Sucesso!',
                    html: 'Novo questinário cadastrado.',
                    type: 'success',
                    onClose: () => {
                        window.location.reload();
                    }
                });
            }
        });
        
    }
    
    function showEdit(cod){
        $('.edit').hide();
        $('.add').hide();
        $.ajax({
            url: '/questionario/buscar-questionario',
            data: {questionario : cod},
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = JSON.parse(retorno);
                Swal.close();
                if(retorno.response){
                    $('#edit_panel_respostas').hide();
                    $('#edit_desc').val(retorno.titulo);
                    $('#cod_questionario').val(retorno.cod_questionario);
                    $('#tipo_questionario').val(retorno.tipo_questionario);
                    $('#perguntas_edit').html(retorno.html);
                    $('#edit-menu-objetiva').hide();
                    $('#menu-objetiva2').hide();
                    $('#menu-dissertativa2').hide();
                    $('#btn_add_dependencia').hide();
                    $('#edit_questionario_desc').attr('disabled', true);
                    $('#modalEdit').modal('show');
                }else{
                    Swal.fire({
                        title: 'Atenção!',
                        html: 'Questinario não encontrado.',
                        type: 'info'
                    });
                }
            }
        });
    }
    
    function showDelete(cod){
        
        Swal.fire({
            title: 'Atenção!',
            html: 'Deseja realmente excluir?',
            type: 'info',
            showCancelButton: true,
            preConfirm: () => {
                $.ajax({
                    url: '/questionario/cadastro/deleteQuestionario',
                    data: {questionario : cod},
                    type: 'json',
                    method: 'POST',
                    beforeSend: function () {
                        loader();
                    },
                    success: function (retorno) {
                        Swal.fire({
                            title: 'Sucesso!',
                            html: 'Questionário deletado.',
                            type: 'success',
                            onClose: () => {
                                window.location.reload();
                            }
                        });
                    }
                });
            }
        });
    }
    
    function editQuestionar(){
        
        if(!$('#edit_desc').val()){
            Swal.fire({
                title: 'Atenção!',
                html: 'Digite a descrição sobre o Questionário.',
                type: 'info'
            });
            return false;
        }
            
        $.ajax({
            url: '/questionario/cadastro/editQuestionario',
            data: 
                {
                    questionario    : $('#cod_questionario').val(),
                    descricao       : $('#edit_desc').val()
                },
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                
                if(!retorno.response){
                    Swal.fire({
                        title: 'Opss...',
                        html: retorno.msg,
                        type: 'success'
                    });
                }else{
                    Swal.fire({
                        title: 'Sucesso!',
                        html: 'Descrição do Questionário alterada.',
                        type: 'success'
                    });
                    $('#edit_questionario_desc').attr('disabled', true);
                }
                
            }
        });
    }

</script>