<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix">  
                <div class="row panels">
                    <div class="col-md-12 pd-0" style="clear: both;">
                        <div class="box">                           
                            <div class="icon">
                                <div class="image back-primary3"><i class="fa fa-book"></i>&nbsp;<label class="title">Questionário Inicial</label></div>
                                <div class="info" style="height: 500px">
                                    <div class="col-md-offset-2 col-xs-12 col-md-8" style="margin-top: 10px;">
                                        <h2 class="pergunta">1) Qual o nome do Junior perez?</h2>
                                        <div class="respostas">
                                            <div class="respostas-primary">
                                                <input type="radio" name="radio" id="radio1"/>
                                                <label for="radio1">Judinerson Perez</label>
                                            </div>
                                            <div class="respostas-primary">
                                                <input type="radio" name="radio" id="radio2"/>
                                                <label for="radio2">Denilson Perez Junior</label>
                                            </div>
                                            <div class="respostas-primary">
                                                <input type="radio" name="radio" id="radio3"/>
                                                <label for="radio3">Everaldo Perez</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class='col-md-12' style="margin-top:10px">
                                        <button type='button' class='btn btn-primary4'>Voltar</button>
                                        <button type='button' class='btn btn-primary4'>Continuar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(".img-check").click(function () {
        $(this).toggleClass("resposta-imagem-check");
    });
</script>