<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!-- Include the above in your HEAD tag -->

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<div class="main">


    <div class="container">
        <center>
            <div class="middle">

                <div class="logo">
                    <div class="row" style="margin-top: 20%;">
                        <img src="./img/logo/logo_branco.png" style="width:350px; margin: auto; display: block;">
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div id="login">

                    <form>

                        <fieldset class="clearfix">
                            <h3 style="color:white;">LOGIN</h3>
                            <div style="margin-top:20px">
                                <p ><span class="fa fa-user"></span><input type="text" id="login_email" Placeholder="E-mail" required></p> <!-- JS because of IE support; better: placeholder="Username" -->
                                <p><span class="fa fa-lock"></span><input type="password" id="senha"  Placeholder="Senha" required></p> <!-- JS because of IE support; better: placeholder="Password" -->

                                <div style="margin-top:20px">
                                    <span class="pull-center" style="display: inline-block;"><a href="/cadastro"><input type="button" value="Cadastro"></a>&nbsp;&nbsp;&nbsp;<input type="button" onclick="logar();" style="width:100px" value="Entrar"></span>
                                </div>
                                <div style="margin-top:10px">
                                    <span class="pull-center" style="display: inline-block;"><a style="color:#fff" href="/esqueci-senha">Esqueci minha senha</a></span>
                                </div>
                            </div>

                        </fieldset>
                        <div class="clearfix"></div>
                    </form>

                    <div class="clearfix"></div>

                </div> <!-- end login -->

            </div>
        </center>
    </div>

</div>


<script type="text/javascript">
    
    function logar(){
        
        $.ajax({
            url: '/login/acessar',
            data: {
                login: $('#login_email').val(),
                senha: $('#senha').val(),
            },
            method: 'POST',
            datatype: 'json',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = jQuery.parseJSON(retorno);
                if (!retorno.response) {
                    Swal.fire({
                        type: 'error',
                        title: 'Oops...',
                        text: retorno.msg,
                        footer: '<a href>Esqueceu a senha?</a>'
                    });
                }else{
                    window.location.href = "/";
                }
            },
            error: function () {
            
            },
            complete: function () {

            }
        });
        
    }
    
</script>