<div class="panel-default add" id="add_panel_respostas" style="display:none;margin-bottom: 10px">
    <div class="panel-heading back-primary3" style="border:0px !important">
        Adicionar nova Questão
    </div>
    <div class="panel-body" id="add_nova_pergunta">
        <div id="escolher_tipo_resp text-center" style="text-align: center;">
            <div class="form-group" style="text-align: left">
                <label for="add_desc_resp" class="col-form-label">Digite a pergunta abaixo: <label style="color:red">*</label></label>
                <br>
                <input type="text" class="form-control" id="add_desc_resp" value="">
            </div>
            <button type="button" class="btn btn-primary3" id="btn_objetiva" onclick="escolher_tipo_resp(1);">Objetiva</button>
            <label id="lblou">ou</label>
            <button type="button" class="btn btn-primary3" id="btn_dissertativa" onclick="escolher_tipo_resp(2);">Dissertativa</button>
            <hr>
        </div>
    </div>
</div>
<div class="panel-default add" id="menu-objetiva" style="display:none;margin-bottom: 10px">
    <div class="panel-heading back-primary3" style="border:0px !important">
        Alternativas
    </div>
    <div class="panel-body">
        <label class="col-form-label">Adicione abaixo as alternativas para esta questão: <label style="color:red">*</label></label>
        <div class="respostas">
            <div id="add-respostas-objetiva">
            </div>
            <br>
            <div class="col-md-12 text-right">
                <button type="button" class="btn btn-primary3" onclick="addLimpar();">Limpar Alternativas <i class="fa fa-times"></i></button>
                <button type="button" class="btn btn-primary3" onclick="addAlternativa();">Adicionar Alternativa <i class="fa fa-plus"></i></button>
                <hr>
            </div>
        </div>
    </div>
</div>

<div class="panel-default add" id="div_dependencia_add" style="display:none;margin-bottom:10px;">
    <div class="panel-heading back-primary3" style="border:0px !important">
        Dependência
    </div>
    <div class="panel-body">
        <div class="form-group" style="text-align: left">
            <label for="select_questao_add" class="col-form-label">Selecione a Questão: <label style="color:red">*</label></label>
            <br>
            <select class="form-control" id="select_questao_add">
            </select>
            <br>
            <label for="select_alternativa_add" class="col-form-label">Selecione a Alternativa: <label style="color:red">*</label></label>
            <br>
            <select class="form-control" id="select_alternativa_add">
            </select>
            <hr>
        </div>
    </div>
</div>

<div class='text-right add' id="menu-objetiva0" style="display:none;margin-top: 10px;;margin-bottom: 10px">
    <button type="button" class="btn btn-primary3" id="btn_add_dependencia3" onClick="dependencia(1);">Adicionar Dependência <i class="fa fa-plus"></i></button>
    <button type="button" class="btn btn-primary3" id="btn_cancelar_dependencia3" style="display: none;" onClick="addCancelarDependencia();">Remover Dependência <i class="fa fa-times"></i></button>
    <button type="button" class="btn btn-primary3" onclick="addFinalizar();">Finalizar <i class="fa fa-check"></i></button>
</div>

<div class='text-right add' id="menu-dissertativa" style="display:none;margin-top: 10px;;margin-bottom: 10px">
    <button type="button" class="btn btn-primary3" id="btn_add_dependencia4" onClick="dependencia(1);">Adicionar Dependência <i class="fa fa-plus"></i></button>
    <button type="button" class="btn btn-primary3" id="btn_cancelar_dependencia4" style="display: none;" onClick="addCancelarDependencia();">Remover Dependência <i class="fa fa-times"></i></button>
    <button type="button" class="btn btn-primary3" onclick="addFinalizar2();">Finalizar <i class="fa fa-check"></i></button>
</div>
 
<script type="text/javascript">

    function addQuestao(tipo_qst) {
        $('.edit').hide();
        limparAdd();
        $('#add_panel_respostas').fadeIn('slow');
        $('#edit_panel_respostas').hide();
        
        if(tipo_qst == 2){
            $('#tipo_questionario').val(tipo_qst);
            $('#btn_dissertativa').remove();
            $('#lblou').remove();
        }
    }

    function addAlternativa() {
        if($('#tipo_questionario').val() == 2){
            
            html = '<div class="form-group divRemoverResposta" style="text-align:right;">'+
                    '<i class="fa fa-times pointer removerResposta" style="display:block"></i>' +
                    '<input type="radio" style="display: inline;" name="resposta-correta">'+
                    '&nbsp;'+
                    '&nbsp;'+
                    '<input type="text" maxlength="500" class="form-control" id="add_desc" style="display:inline;width:95%">'+
                    '</div>';
        
        }else{
            html = '<div class="form-group divRemoverResposta" style="text-align:right;">' +
                '<i class="fa fa-times pointer removerResposta"></i>' +
                '<input type="text" maxlength="500" class="form-control" id="add_desc" value="">' +
                '</div>';
        }
        $('#add-respostas-objetiva').append(html);
        
    }

    $('#add-respostas-objetiva').on('click', '.removerResposta', function (e) {
        $(this).parent('.divRemoverResposta').remove();
    });
    
    function addLimpar() {
        $('#add-respostas-objetiva').html('');
    }

    function addFinalizar() {
        var qtdInputs = 0;
        $('#add-respostas-objetiva input[type="text"]').filter(function () {
            return $(this).val() != "" ? qtdInputs = qtdInputs + 1 : '';
        });
        if (qtdInputs <= 0) {
            Swal.fire({
                title: 'Atenção!',
                html: 'Coloque alternativas.',
                type: 'info'
            });
            return false;
        }

        var alternativas = [];
        $('#add-respostas-objetiva input[type="text"]').filter(function () {
            
            if($(this).val() != ""){
                push = $(this).val();
                
                if($('#tipo_questionario').val() == 2){
                    if($(this).prev().is(':checked')){
                        push = push + '|' + '1';
                    }else{
                        push = push + '|' + '0';
                    }
                }
                return alternativas.push(push);
            }
            
        });
        
        var dependencia = addVerificaDependencia();
        
        if (!$('#add_desc_resp').val()) {
            Swal.fire({
                title: 'Atenção!',
                html: 'Digite a questão.',
                type: 'info'
            });
            return false;
        }
        
        if($('#tipo_questionario').val() == 2){
            var qtdInputs = 0;
            $('#add-respostas-objetiva input[type="radio"]').filter(function () {
                return $(this).is(':checked') != "" ? qtdInputs = qtdInputs + 1 : '';
            });

            if (qtdInputs <= 0) {
                Swal.fire({
                    title: 'Atenção!',
                    html: 'Selecione a alternativa correta.',
                    type: 'info'
                });
                return false;
            }

            if(qtdInputs > 1){
                Swal.fire({
                    title: 'Atenção!',
                    html: 'Selecione apenas uma alternativa correta.',
                    type: 'info'
                });
                return false;
            }
        }

        $.ajax({
            url: '/questionario/cadastro/add-questao',
            data: {
                cod_questionario: $('#cod_questionario').val(),
                desc_questao: $('#add_desc_resp').val(),
                cod_questao: '0',
                alternativas: alternativas,
                tipo_questao: '1',
                dependencia_questao : dependencia.cod_questao,
                dependencia_alternativa : dependencia.cod_alternativa,
                tipo : 1,
                tipo_qst : $('#tipo_questionario').val()
            },
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = JSON.parse(retorno);
                
                if(!retorno.response){
                    Swal.fire({
                        title: 'Atenção!',
                        html: retorno.msg,
                        type: 'info'
                    });
                    return false;
                }else{
                    $('#perguntas_edit').html(retorno.html);
                    Swal.fire({
                        title: 'Sucesso!',
                        html: 'Questão adicionada.',
                        type: 'success'
                    });

                    limparAdd();
                }
            }
        });
    }
    
    function addFinalizar2() {
        
        var dependencia = addVerificaDependencia();
        
        if(!dependencia){
            return false;
        }
        
        if (!$('#add_desc_resp').val()) {
            Swal.fire({
                title: 'Atenção!',
                html: 'Digite a questão.',
                type: 'info'
            });
            return false;
        }
        
        $.ajax({
            url: '/questionario/cadastro/add-questao',
            data: {
                cod_questionario: $('#cod_questionario').val(),
                desc_questao: $('#add_desc_resp').val(),
                cod_questao: '0',
                alternativas: [],
                tipo_questao: '2',
                dependencia_questao : dependencia.cod_questao,
                dependencia_alternativa : dependencia.cod_alternativa,
                tipo : 1
            },
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = JSON.parse(retorno);
                
                if(!retorno.response){
                    Swal.fire({
                        title: 'Atenção!',
                        html: retorno.msg,
                        type: 'info'
                    });
                    return false;
                }else{
                    $('#perguntas_edit').html(retorno.html);
                    Swal.fire({
                        title: 'Sucesso!',
                        html: 'Questão adicionada.',
                        type: 'success'
                    });

                    limparAdd();
                }
            }
        });
    }
    
    function addVerificaDependencia(){
        var dependencia = {cod_questao : 0, cod_alternativa : 0};
        
        var has_dependencia = ($('#btn_cancelar_dependencia3').is(':visible') || $('#btn_cancelar_dependencia4').is(':visible'));
        
        if(has_dependencia){
            var cod_dependencia = $('#select_questao_add').val();
            if(!cod_dependencia || cod_dependencia == 0){
                Swal.fire({
                    title: 'Atenção!',
                    html: 'Selecione a questão pendente.',
                    type: 'info'
                });
                return false;
            }else{
                dependencia.cod_questao = cod_dependencia;
                cod_dependencia = $('#select_alternativa_add').val();
                if((!cod_dependencia || cod_dependencia == 0) && $('#select_alternativa_add').is(':visible')){
                    Swal.fire({
                        title: 'Atenção!',
                        html: 'Selecione a alternativa da questão pendente.',
                        type: 'info'
                    });
                    return false;
                }else{
                    if(!$('#select_alternativa_add').is(':visible')){
                        dependencia.cod_alternativa = 0;
                    }else{
                        dependencia.cod_alternativa = cod_dependencia;
                    }
                    return dependencia;
                }
            }
        }else{
            return {cod_questao : 0, cod_alternativa : 0};
        }
    }

    function limparAdd() {
        $('#btn_objetiva').attr('style', 'background:#629bad !important');
        $('#btn_dissertativa').attr('style', 'background:#629bad !important');
        $('#menu-dissertativa').hide();
        $('#menu-objetiva').hide();
        $('#add-respostas-objetiva').html('');
        $('#add_desc_resp').val('');
        $('#add_panel_respostas').hide();
        $('#div_dependencia_add').hide();
        $('.add').hide();
    }


    function escolher_tipo_resp(tipo) {

        if (!$('#add_desc_resp').val()) {
            Swal.fire({
                title: 'Atenção!',
                html: 'Antes de escolher o tipo da questão, digite a questão.',
                type: 'info'
            });
            return false;
        }
        
        addCancelarDependencia();
        
        if($('#tipo_questionario').val() == 2){
            $('#btn_add_dependencia3').remove();
        }

        if (tipo == 1) {
            $('#btn_objetiva').attr('style', 'background:#477482 !important');
            $('#btn_dissertativa').attr('style', 'background:#629bad !important');
            $('#menu-dissertativa').hide();
            $('#menu-objetiva').fadeIn('slow');
            $('#menu-objetiva0').fadeIn('slow');
        } else {
            $('#btn_objetiva').attr('style', 'background:#629bad !important');
            $('#btn_dissertativa').attr('style', 'background:#477482 !important');
            $('#menu-objetiva').hide();
            $('#menu-objetiva0').hide();
            $('#menu-dissertativa').fadeIn('slow');
        }
        
    }
    
    function addShowDependencia(){
        $('#div_dependencia_add').show();
        $('#btn_cancelar_dependencia3').show();
        $('#btn_add_dependencia3').hide();
        $('#btn_cancelar_dependencia4').show();
        $('#btn_add_dependencia4').hide();
    }
    
    function addCancelarDependencia(){
        $('#div_dependencia_add').hide();
        $('#select_questao_add').html('');
        $('#select_alternativa_add').html('');
        
        $('#btn_cancelar_dependencia3').hide();
        $('#btn_add_dependencia3').show();
        $('#btn_cancelar_dependencia4').hide();
        $('#btn_add_dependencia4').show();
    }
    
    $('#select_questao_add').on('change', function(){
        tipo = 2;
        
        dependencia(tipo,$(this).val());
    });

    function showAdd() {
        $('#modalAdd').modal('show');
    }
    
    function dependencia(tipo){
        addShowDependencia();
        $.ajax({
            url: '/questionario/cadastro/buscar-questao',
            data: {
                questionario: $('#cod_questionario').val(),
                questao: tipo == 1 ? 0 : $('#select_questao_add').val(),
                tipo: tipo
            },
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = JSON.parse(retorno);
                
                if(!retorno.response){
                    Swal.fire({
                        title: 'Atenção!',
                        html: 'Essa questão não possui alternativas sem dependencia. Por favor selecione outra questão.',
                        type: 'info'
                    });
                    return false;
                }
                
                Swal.close();
                if(tipo == 1){
                    $('#select_questao_add').html('');
                    $('#select_questao_add').append("<option value='0'>Selecionar</option>");
                    for(var i=0; i < retorno.questao.length; i++){
                        $('#select_questao_add').append("<option value='"+retorno.questao[i].cod+"'>"+retorno.questao[i].desc_pergunta+"</option>");
                    }
                }else{
                    $('#select_alternativa_add').html('');
                    if(retorno.alternativas.length > 0){
                        $('#select_alternativa_add').show();
                        $('[for="select_alternativa_add"').show();
                        $('#select_alternativa_add').append("<option value='0'>Selecionar</option>");
                        for(var i=0; i < retorno.alternativas.length; i++){
                            $('#select_alternativa_add').append("<option value='"+retorno.alternativas[i].cod+"'>"+retorno.alternativas[i].desc_pergunta+"</option>");
                        }
                    }else{
                        $('#select_alternativa_add').hide();
                        $('[for="select_alternativa_add"]').hide();
                    }
                }
            }
        });
    }

</script>    