<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!-- Include the above in your HEAD tag -->

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<div class="main">
<style>
    #login form input {
	height: 40px;
    }    
    #login form span.fa {
        height: 40px;
        line-height: 42px;
    }
</style>
    <div class="container">
        <center>
            <div class="middle">
                
                <div class="logo">
                    <div class="row" style="margin-top: 30%;">
                        <img src="./img/logo/logo_branco.png" style="width:350px; margin: auto; display: block;">
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div id="login">

                    <form action="/" method="post">
                        <fieldset class="clearfix">
                            <h3 style="color:white;">PRÉ-CADASTRO</h3>
                            <div style="margin-top:20px">
                            <p ><span class="fa fa-user"></span><input type="text"  Placeholder="Nome" id="nome" required></p>
                            <p ><span class="fa fa-envelope"></span><input type="text"  Placeholder="E-mail" id="email" required></p>
                            <p ><span class="fa fa-book"></span>
                                <select name="categoria" id="escolaridade" style="color:gray">
                                            <option value="0">Escolaridade</option>
                                            <option value="1">Doutorado</option>
                                            <option value="2">Graduação</option>
                                            <option value="3">Pós-Graduação</option>
                                            <option value="4">Mestrado</option>
                                            <option value="5">Pós-Doutorado</option>
                                            <option value="7">Tecnólogo </option>
                                </select></p>
                            <p ><span class="fa fa-lock"></span><input type="password"  Placeholder="Senha" id="senha" required></p>
                            <p ><span class="fa fa-lock"></span><input type="password"  Placeholder="Confirmção da Senha" id="conf_senha" required></p>
                            
                            </div>
                            <div style="margin-top:20px">
                                <span class="pull-center" style="display: inline-block;">
                                    <a href="/login">
                                        <input type="button" style="width:100px" value="Voltar">
                                    </a>
                                    &nbsp;&nbsp;&nbsp;
                                    <input type="button" style="width:100px" value="Enviar" onclick="novo()">
                                </span>
                            </div>
                        </fieldset>
                        <div class="clearfix"></div>
                    </form>

                    <div class="clearfix"></div>

                </div> <!-- end login -->

            </div>
        </center>
    </div>

</div>


<script type="text/javascript">
    
    function novo(){
        var data = {
            nome            : $('#nome').val(),
            email           : $('#email').val(),
            escolaridade    : $('#escolaridade').val(),
            senha           : $('#senha').val()
        };
        
        if(!validaParametros(data)){
            Swal.fire({
                title: 'Atenção!',
                html: "Digite todos os campos.",
                type: 'info'
            });
            return false;
        }
        
        if($('#senha').val() != $('#conf_senha').val()){
            Swal.fire({
                title   : 'Atenção!',
                html    : "Senha e confirmação de senha são diferentes.",
                type    : 'info'
            });
            return false;
        }
        
        $.ajax({
            url: '/cadastro/novo',
            data: data,
            method: 'POST',
            datatype: 'json',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = jQuery.parseJSON(retorno);
                if (retorno.response) {
                    Swal.fire({
                        type: 'success',
                        title: 'Sucesso!',
                        html: retorno.msg,
                        onClose: () => {
                            window.location.href = '/login';
                        }
                    });
                }else{
                    Swal.fire({
                        type: 'info',
                        title: 'Atenção!',
                        html: retorno.msg
                    });
                }
            },
            error: function () {

            },
            complete: function () {

            }
        });
        
    }
    
</script>