<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!-- Include the above in your HEAD tag -->

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<div class="main">
<style>
    #login form input {
	height: 40px;
    }    
    #login form span.fa {
        height: 40px;
        line-height: 42px;
    }
</style>
    <div class="container">
        <center>
            <div class="middle">
                
                <div class="logo">
                    <div class="row" style="margin-top: 30%;">
                        <img src="./img/logo/logo_branco.png" style="width:350px; margin: auto; display: block;">
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div id="login">

                    <form action="/" method="get">
                        <fieldset class="clearfix">
                            <h3 style="color:white;">PRÉ-CADASTRO</h3>
                            <div style="margin-top:20px">
                            <p ><span class="fa fa-user"></span><input type="text"  Placeholder="Nome" required></p>
                            <p ><span class="fa fa-envelope"></span><input type="text"  Placeholder="E-mail" required></p>
                            <p ><span class="fa fa-book"></span>
                                <select name="categoria" id="categoria" style="color:gray">
                                            <option value="">Escolaridade</option>
                                            <option value="1">Doutorado</option>
                                            <option value="2">Graduaçao</option>
                                            <option value="3">Pós-Graduaçao</option>
                                            <option value="4">Mestrado</option>
                                            <option value="5">Pós-Doutorado</option>
                                            <option value="7">Tecnólogo </option>
                                </select></p>
                            <p ><span class="fa fa-lock"></span><input type="text"  Placeholder="Senha" required></p>
                            <p ><span class="fa fa-lock"></span><input type="text"  Placeholder="Confirmação da Senha" required></p>
                            
                            </div>
                            <div style="margin-top:20px">
                                <span class="pull-center" style="display: inline-block;"><a href="/login"><input type="button" style="width:100px" value="Voltar"></a>&nbsp;&nbsp;&nbsp;<input type="submit" style="width:100px" value="Enviar"></span>
                            </div>
                        </fieldset>
                        <div class="clearfix"></div>
                    </form>

                    <div class="clearfix"></div>

                </div> <!-- end login -->

            </div>
        </center>
    </div>

</div>