<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix mt">            
                <div class="container pd-0">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-6 pd-0">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-user"></i></div>
                                    <div class="info" style="height: 447px;padding:30px;">
                                        <h3 class="title">Pré-Cadastro</h3>
                                        <hr>
                                        <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12 pd-0">                    
                                            <form id="frmPreCadastro" action="" method="post" class="form">
                                                <div class="row" style="margin-bottom: 20px">
                                                    <div class="col-md-12 text-left">
                                                        <label class="control-label" for="nome">Nome:</label>
                                                        <input name="nome" class="form-control" placeholder="Digite aqui o Nome" type="text">
                                                    </div>
                                                </div>

                                                <div class="row" style="margin-bottom: 20px">
                                                    <div class="col-md-12 text-left">
                                                        <label class="control-label" for="email">Email:</label>
                                                        <input name="email" class="form-control" placeholder="Digite aqui o Email" type="text">
                                                    </div>
                                                </div>

                                                <div class="row" style="margin-bottom: 20px">
                                                    <div class="col-md-12 text-left">
                                                        <label class="control-label" for="district">Escolaridade:</label>
                                                        <select name="district" class="form-control">
                                                            <option value="">Selecione</option>
                                                            <option value="1">Doutorado</option>
                                                            <option value="2">Graduação</option>
                                                            <option value="3">Pós-Graduação</option>
                                                            <option value="4">Mestrado</option>
                                                            <option value="5">Pós-Doutorado</option>
                                                            <option value="7">Tecnólogo </option>
                                                        </select>
                                                    </div>
                                                </div>

                                                <div class="row">
                                                    <div class="col-md-12 text-left">
                                                        <button type="button" class="btn btn-primary3 btn-block info">Enviar <i class="fa fa-check"></i></button>
                                                    </div>
                                                </div>    
                                            </form>
                                        </div>                                                              
                                    </div>
                                </div>
                            </div> 
                        </div>
                    </div>      
                </div>
            </div>
        </div>
    </div>
</div>
<div class="page-content">
    <div id="footer">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="col-xs-12">
                    <div align="center" style="margin:10px;"><img src="./img/unesp.png" alt="" class="unesp"></div>
                </div>    
            </div> 
        </div>
    </div>    
</div>