<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix mt">            
                <div class="container pd-0">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-6 pd-0">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary2"><i class="fa fa-user"></i>&nbsp;<label class="title">Pré-Cadastro</label></div>
                                    <div class="info" style="height: 447px;padding:30px;">
                                        <hr>
                                        <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12 pd-0">                    
                                            <form id="frmPreCadastro" action="/pre-cadastro/novo" method="post" class="form">
                                                <div class="row" style="margin-bottom: 20px">
                                                    <div class="col-md-12 text-left">
                                                        <label class="control-label" for="nome">Nome:</label><label style="color:red">*</label>
                                                        <input name="nome" id="nome" class="form-control" placeholder="Digite aqui o Nome" type="text">
                                                    </div>
                                                </div>

                                                <div class="row" style="margin-bottom: 20px">
                                                    <div class="col-md-12 text-left">
                                                        <label class="control-label" for="email">Email:</label><label style="color:red">*</label>
                                                        <input name="email" id="email" class="form-control" placeholder="Digite aqui o Email" type="text">
                                                    </div>
                                                </div>

                                                <div class="row" style="margin-bottom: 20px">
                                                    <div class="col-md-12 text-left">
                                                        <label class="control-label" for="escolaridade">Escolaridade:</label><label style="color:red">*</label>
                                                        <select name="escolaridade" id="escolaridade" class="form-control">
                                                            <option value="">Selecionar Escolaridade</option>
                                                            <?php foreach($escolaridades as $dados):?>
                                                                    <option value="<?= $dados['cod_nivel'] ?>"><?= $dados['descricao'] ?></option>
                                                            <?php endforeach; ?>
                                                        </select>
                                                    </div>
                                                </div>

                                                <div class="row">
                                                    <div class="col-md-12 text-left">
                                                        <button type="button" onClick="enviar()" class="btn btn-primary3 btn-block info" onclick="">Enviar <i class="fa fa-check"></i></button>
                                                    </div>
                                                </div>    
                                            </form>
                                        </div>                                                              
                                    </div>
                                </div>
                            </div> 
                        </div>
                    </div>      
                </div>
            </div>
        </div>
    </div>
</div>
<div class="page-content">
    <div id="footer">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="col-xs-12">
                    <div align="center" style="margin:10px;"><img src="/img/logo/unesp.png" alt="" class="unesp"></div>
                </div>    
            </div> 
        </div>
    </div>    
</div>

<script type="text/javascript">
    
    $('#escolaridade').on('click', function(){
        $(this).children('option[value=""]').remove();
    });
    
    function enviar(){
        
        var data = {
            nome: $('#nome').val(),
            email: $('#email').val(),
            escolaridade: $('#escolaridade').val()
        };
    
        if(!validaParametros(data)){
            Swal.fire({
                title: 'Atenção!',
                html: "Digite todos os campos obrigatórios (*)",
                type: 'info'
            });
            return false;
        }
    
        $.ajax({
            url: '/pre-cadastro/novo',
            data: data,
            method: 'POST',
            datatype: 'json',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = jQuery.parseJSON(retorno);
                if (!retorno.response) {
                    Swal.fire({
                        type: 'info',
                        title: 'Oops...',
                        text: retorno.msg,
                    });
                }else{
                    Swal.fire({
                        type: 'success',
                        title: 'Sucesso!',
                        html: 'Novo membro cadastrado com sucesso!<br>Informações para o acesso foram enviadas ao email do novo membro.',
                        onClose: () => {
                            window.location.reload();
                        }
                    });
                }
            },
            error: function () {

            },
            complete: function () {

            }
        });
    }
    
    
</script>