<header class="navbar navbar-min" id="header-navbar">
    <div class="container">
        <a id="logo" class="navbar-brand pz" href="/">
            <div align="center" style="margin:10px;"><img src="/img/logo/logo_branco.png" alt="" class="normal-logo logo-white imglogo"></div>
        </a>
        <div class="nav-no-collapse pull-right" id="header-nav"> 
            <ul class="nav navbar-nav pull-left Professor-id nav-id height-padrao">                                                  

                <li class="margin-poweroff">
                    <a onclick="sair()" class="pointer"><i class="fa fa-sign-in faa-tada"></i>&nbsp;Sair</a>
                </li>
            </ul>
        </div>
    </div>
</div>
</header>


<script type="text/javascript">
    
    function sair(){
        $.ajax({
            url: '/login/logout',
            method: 'POST',
            datatype: 'json',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = jQuery.parseJSON(retorno);
                if(retorno.response){
                    window.location.href = "/login";
                }
            },
            error: function () {
            
            },
            complete: function () {

            }
        });
    }
    
    
</script>