<nav class="navbar navbar-inverse navbar-hinode sidebar larg-nav" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header ">
            <a href="/" style="width:90%; margin-top: 10px;" data-toggle="tooltip" data-placement="bottom" title="Página Inicial!" class="botao-min border-bottom btn btn-primary3 btn-pad" id="botaoPrincipal">
                <strong><span class="hidden-xs showopacity fa fa-home icon-ajuste"></span> <span class="menu-item hid-menu">Pagina Inicial</span></strong>
            </a>

            <div class="btn-topo">
                <div class="img-perfil" style="margin-botton: -10px">
                    <img class="img img-Professor" src="/img/semfoto.png" onerror="$(this).attr('src','/img/semfoto.png');">
                    <a onclick="modalFrame('/foto-perfil', '', false);" title="Alterar Foto" class="pointer"><span class="fa fa-camera"></span></a>
                </div>
                <ul class="nav pull-left Professor-id nav-id height-padrao">
                    <li class="dropdown mt-7">
                        <a href="javascript:;" id="make-small-nav" data-toggle="dropdown" class="dropdown-toggle" data-click="toggle-notify">
                            <span class="usuario-id" style="color:black">Vivangola Perez da Silva Cardoso</span>
                        </a>
                        <div class="row">
                            <i class="fa fa-calendar-o"></i>&nbsp;<span id="day_painel"><?= date('y/m/d') ?></span>
                            &nbsp;&nbsp;
                            <i class="fa fa-clock-o"></i>&nbsp;<span id="time_painel"><?= date('H:i:s') ?></span>
                        </div>

                        <br/>
                        <ul class="dropdown-menu dropdown-notification dropdown-menu-right" id='infoEnvelope'>
                            <li class="dropdown-header">
                                <a style="padding-left: 10px; font-size: 14px;" href="/perfil" class="faa-parent animated-hover"><i class="fa fa-cog faa-spin"></i>&nbsp;Meu Perfil</a>
                            </li>
                            <li class="dropdown-header">
                                <a style="padding-left: 10px; font-size: 14px;" href="/alterar/senha" class="faa-parent animated-hover"><i class="fa fa-key faa-shake"></i>&nbsp;Alterar Senha</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <hr>
        <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-nav-new nav-list hoverzinho-menu">
                <li>
                    <a class="<?= $pagina == 'atas' ? 'selected-link' : '' ?>" href="/atas">
                        <span class="hidden-xs showopacity fa fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Atas de Reuniões</span>
                    </a>
                </li>
                <li>
                    <a class="<?= $pagina == 'biblioteca' ? 'selected-link' : '' ?>" href="/biblioteca">
                        <span class="hidden-xs showopacity fa fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Biblioteca</span>
                    </a>
                </li>
                <li>
                    <a class="<?= $pagina == 'pre-cadastro' ? 'selected-link' : '' ?> " href="/pre-cadastro">
                        <span class="hidden-xs showopacity fa fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Cadastrar</span>
                    </a>
                </li>
                <li>
                    <a class="<?= $pagina == 'chat' ? 'selected-link' : '' ?>" href="/chat">
                        <span class="hidden-xs showopacity fa fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Chat</span>
                    </a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle <?= $pagina == 'configuracoes' ? 'selected-link' : '' ?>" data-toggle="dropdown">
                        <span class="hidden-xs showopacity icon-ajuste fa fa-chevron-circle-right"></span> <span class="menu-item-2 hid-menu">Configurações
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#" class="dropdown-toggle <?= $pagina == 'email' ? 'selected-link' : '' ?>" data-toggle="dropdown">
                        <span class="hidden-xs showopacity icon-ajuste fa fa-chevron-circle-right"></span> <span class="menu-item-2 hid-menu">E-mails</span> <span class=" fa fa-chevron-down pull-right sumir-icon-angle mt-10"></span>

                    </a>
                    <ul class="submenu dropdown-menu forAnimate" role="menu">
                        <li><a href="/relatorio/carta-compromisso/painel">Enviar E-mail                                            
                            </a>
                        </li>
                        <li><a href="/relatorio/carta-compromisso">Meus E-mails                                          
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a class="<?= $pagina == 'avisos' ? 'selected-link' : '' ?>" href="/avisos">
                        <span class="hidden-xs showopacity fa  fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Quadro de Avisos</span>
                    </a>
                </li>
                <li>
                    <a class="<?= $pagina ?> <?= $pagina == 'quadro-disponibilidade' ? 'selected-link' : '' ?>" href="/quadro-disponibilidade">
                        <span class="hidden-xs showopacity fa  fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Quadro de Disponibilidade</span>
                    </a>
                </li>
                <li>
                    <a class="<?= $pagina == 'eventos' ? 'selected-link' : '' ?>" href="/eventos">
                        <span class="hidden-xs showopacity fa fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Quadro de Eventos</span>
                    </a>

                </li>
                <li>
                    <a class="<?= $pagina == 'quadro-leitura' ? 'selected-link' : '' ?>" href="/quadro-leitura">
                        <span class="hidden-xs showopacity fa fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Quadro de Literatura</span>
                    </a>
                </li>
                <li>
                    <a class="<?= $pagina == 'escolaridade' ? 'selected-link' : '' ?> " href="/escolaridade">
                        <span class="hidden-xs showopacity fa  fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Níveis de Escolaridade</span>
                    </a>
                </li>
                <li>
                    <a class="<?= $pagina == 'plano-atividades' ? 'selected-link' : '' ?>" href="/plano-atividades">
                        <span class="hidden-xs showopacity fa fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Plano de Atividade</span>
                    </a>
                </li>
                <li>
                    <a class="<?= $pagina == 'plano-metas' ? 'selected-link' : '' ?> " href="/plano-metas">
                        <span class="hidden-xs showopacity fa fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Plano de Metas</span>
                    </a>
                </li>
                <li>
                    <a class="<?= $pagina == 'producao-grupo' ? 'selected-link' : '' ?>" href="/producao-grupo">
                        <span class="hidden-xs showopacity fa fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Produçao do Grupo</span>
                    </a>
                </li>
                <li class="list-group-item">
                    <div class="toggle">
                        <span class="hidden-xs showopacity fa fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Questionários</span> <span class="fa fa-chevron-down pull-right sumir-icon-angle mt-10"></span>
                        <div class="list-group-item-sub">
                            <div>
                                <a href="/relatorio/carta-compromisso/painel">Questionários de Aprendizagem</a>
                            </div>
                            <div>
                                <a href="/relatorio/carta-compromisso">Questionário de Cadastro</a>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="toggle">
                        <span class="hidden-xs showopacity fa fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Trabalhos de Correção</span> <span class="fa fa-chevron-down pull-right sumir-icon-angle mt-10"></span>
                        <div class="list-group-item-sub">
                            <div>
                                <a href="/relatorio/carta-compromisso/painel">Meus Trabalhos</a>
                            </div>
                            <div>
                                <a href="/relatorio/carta-compromisso">Trabalhos Recebidos</a>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="toggle">
                        <span class="hidden-xs showopacity fa fa-chevron-circle-right icon-ajuste"></span> <span class="menu-item hid-menu">Usuários</span> <span class="fa fa-chevron-down pull-right sumir-icon-angle mt-10"></span>
                        <div class="list-group-item-sub">
                            <div>
                                <a href="/relatorio/top-recrutadores">Grupos</a>
                            </div>
                            <div>
                                <a href="/relatorio/top-recrutadores">Membros</a>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>


<script type="text/javascript">
    //inicializar menu lateral
    $(document).ready(function() {
        $('.list-group-item-sub').hide();
        $('.toggle').click(function() {
            $(this).children('div').stop().slideToggle();
        });
    });

    function startTime() {
        var today = new Date();
        var h = today.getHours();
        var m = today.getMinutes();
        var s = today.getSeconds();
        // add a zero in front of numbers<10
        m = checkTime(m);
        s = checkTime(s);
        $('#time_painel').text(h + ":" + m + ":" + s);
        t = setTimeout('startTime()', 500);
    }

    function checkTime(i) {
        if (i < 10) {
            i = "0" + i;
        }
        return i;
    }

</script>