<div class="main-content">
    <div class="page-content">
        <div id="footer">
            <div class="row">
                <div class="col-xs-5 col-xs-offset-6 col-md-5 col-md-offset-8">
                    <div class="col-xs-12">
                        <div align="center" style="margin:10px;"><img src="/img/logo/unesp.png" alt="" class="unesp">&copy; 2019 - <?= date('Y') ?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>