<style>
    
    .main-box {
        background: #e3eaf3 !important;
    }
    
    h1{
        color: #477482 !important;
    }
    
</style>

<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix mt">            
                <div class="error-content">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 ">
                                <div class="error-text">
                                    <h1 class="error" style="font-size: 70px">404 Error</h1>
                                    <div class="erro-icon" style="font-size: 50px">
                                        <i class="fa fa-frown-o"></i>
                                    </div>
                                    <h3 style="color:black;text-shadow: none;">Oops! Essa página não pode ser encontrada!</h3>
                                    <p>Desculpe, a página que você está procurando não existe, foi removida ou alterada.</p>
                                    <br>
                                    <a href="/" class="btn btn-primary-borded2 btn-round">Ir para página principal</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
