<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix mt">            
                <div class="container pd-0">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-6 pd-0">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary2"><i class="fa fa-user"></i>&nbsp;<label class="title">Alterar Senha</label></div>
                                    <div class="info" style="height: 447px;padding:30px;">
                                        <hr>
                                        <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12 pd-0">                    
                                            <form id="frmPreCadastro" action="" method="post" class="form">
                                                <div class="row" style="margin-bottom: 20px">
                                                    <div class="col-md-12 text-left">
                                                        <label class="control-label" for="senha_ant">Senha Anterior:</label>
                                                        <input name="senha_ant" id="senha_ant" class="form-control" placeholder="Digite aqui a senha anterior" type="password">
                                                    </div>
                                                </div>
                                                <br>
                                                
                                                <div class="row" style="margin-bottom: 20px">
                                                    <div class="col-md-12 text-left">
                                                        <label class="control-label" for="senha_nova">Nova Senha:</label>
                                                        <input name="senha_nova" id="senha_nova" class="form-control" placeholder="Digite aqui a nova senha" type="password">
                                                    </div>
                                                    <div class="col-md-12 text-left">
                                                        <div class="progress" style="height: 20px !important">
                                                            <div id="progress-bar" class="progress-bar" ></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                
                                                <div class="row" style="margin-bottom: 20px">
                                                    <div class="col-md-12 text-left">
                                                        <label class="control-label" for="senha_nova_conf">Confirmação da Nova Senha:</label>
                                                        <input name="senha_nova_conf" id="senha_nova_conf" class="form-control" placeholder="Digite aqui a confirmação da nova senha" type="password">
                                                    </div>
                                                </div>

                                                <div class="row">
                                                    <div class="col-md-12 text-left">
                                                        <button type="button" class="btn btn-primary3 btn-block info" onclick="alterar()">Alterar <i class="fa fa-check"></i></button>
                                                    </div>
                                                </div>    
                                            </form>
                                        </div>                                                              
                                    </div>
                                </div>
                            </div> 
                        </div>
                    </div>      
                </div>
            </div>
        </div>
    </div>
</div>
<div class="page-content">
    <div id="footer">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="col-xs-12">
                    <div align="center" style="margin:10px;"><img src="./img/unesp.png" alt="" class="unesp"></div>
                </div>    
            </div> 
        </div>
    </div>    
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.2.0/zxcvbn.js" type="text/javascript"></script>
<script type="text/javascript">
    
    $(function() {
        $.fn.bootstrapPasswordMeter = function(options) {
          var settings = $.extend({
            minPasswordLength: 1,
            level0ClassName: 'progress-bar-danger',
            level0Description: 'Senha Fraca',
            level1ClassName: 'progress-bar-danger',
            level1Description: 'Senha Fraca',
            level2ClassName: 'progress-bar-warning',
            level2Description: 'Senha Média',
            level3ClassName: 'progress-bar-success',
            level3Description: 'Senha Forte',
            level4ClassName: 'progress-bar-success',
            level4Description: 'Senha Muito Forte',
          }, options || {});

          $('#senha_nova').on("keyup", function() {
            var progressBar = $('#progress-bar');
            var progressBarWidth = 0;
            var progressBarDescription = '';
            if ($(this).val().length >= 1) {
                var zxcvbnObj = zxcvbn($(this).val());
                progressBar.removeClass(settings.level0ClassName)
                  .removeClass(settings.level1ClassName)
                  .removeClass(settings.level2ClassName)
                  .removeClass(settings.level3ClassName)
                  .removeClass(settings.level4ClassName);
                switch (zxcvbnObj.score) {
                    case 0:
                        progressBarWidth = 25;
                        progressBar.addClass(settings.level0ClassName);
                        progressBarDescription = settings.level0Description;
                        break;
                    case 1:
                        progressBarWidth = 25;
                        progressBar.addClass(settings.level1ClassName);
                        progressBarDescription = settings.level1Description;
                        break;
                    case 2:
                        progressBarWidth = 50;
                        progressBar.addClass(settings.level2ClassName);
                        progressBarDescription = settings.level2Description;
                        break;
                    case 3:
                        progressBarWidth = 75;
                        progressBar.addClass(settings.level3ClassName);
                        progressBarDescription = settings.level3Description;
                        break;
                    case 4:
                        progressBarWidth = 100;
                        progressBar.addClass(settings.level4ClassName);
                        progressBarDescription = settings.level4Description;
                        break;
                }
            } else {
                progressBarWidth = 0;
                progressBarDescription = '';
            }
            progressBar.css('width', progressBarWidth + '%');
            progressBar.text(progressBarDescription);
          });
        };
        $('#senha_nova').bootstrapPasswordMeter({minPasswordLength:3});
      });
  

    function alterar(){
            
            var data = {
                senha_ant       : $('#senha_ant').val(),
                senha_nova      : $('#senha_nova').val(),
                senha_nova_conf : $('#senha_nova_conf').val()
            };
            
            
            if(!validaParametros(data)){
                Swal.fire({
                    title: 'Atenção!',
                    html: "Digite todos os campos.",
                    type: 'info'
                });
                return false;
            }

            if(data.senha_nova != data.senha_nova_conf){
                Swal.fire({
                    title   : 'Atenção!',
                    html    : "Senha e confirmação de senha são diferentes.",
                    type    : 'info'
                });
                return false;
            }
            
            var zxcvbnObj = zxcvbn(data.senha_nova);
            if(zxcvbnObj.score < 2){
                Swal.fire({
                    title   : 'Atenção!',
                    html    : "Para criar uma conta mais segura, por favor digite uma senha média, forte ou muito forte.",
                    type    : 'info'
                });
                return false;
            }
            
            $.ajax({
                url: '/perfil/salvarSenha',
                data: data,
                method: 'POST',
                datatype: 'json',
                beforeSend: function () {
                    loader();
                },
                success: function (retorno) {
                    retorno = jQuery.parseJSON(retorno);
                    if (!retorno.response) {
                        Swal.fire({
                            type: 'info',
                            title: 'Atenção!',
                            text: retorno.msg,
                        });
                    }else{
                        Swal.fire({
                            type: 'success',
                            title: 'Sucesso!',
                            html: retorno.msg,
                            onClose: () => {
                                window.location.reload();
                            }
                        });
                    }
                },
                error: function () {

                },
                complete: function () {

                }
            });
    }
    
</script>