<style>
    .selected{
        background-color: #dceaef;
        border-bottom: 3px solid #a4c2cc;
    }
    .arred{
        border-radius: 5px;
        line-height: 70px;
    }
    .image{
        width: 40% !important;
    }
</style>
<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix mt">            
                <div class="container pd-0">
                    <div class="row">
                        <div class="col-md-12 pd-0" >
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary2 panels"><i class="fa fa-user"></i>&nbsp;<label class="title">Perfil</label></div>
                                    <div class="info" style="height:850px; padding:30px">
                                        <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12 pd-0">                    
                                            <div class="new-color-1 border-new-color-1"> 
                                                <b class="cinza-escuro">&nbsp;</b>
                                            </div> 
                                            <div class="table-responsive">
                                                <table class="table table-striped table-bordered" >    
                                                    <tr class="font-min">
                                                        <td align="left">
                                                            <div class="widget-body" style="padding-left:30px; padding-right:30px">
                                                                <div class="widget-main">
                                                                    <div class="row" id="dvCadastro"> 
                                                                        <form id="frmDados" method="post" >
                                                                            <div class="row" style="margin:20px"> 
                                                                                <div class="col-md-3 selected pointer arred" id="pessoais"> 
                                                                                    <h3 style="margin-left:-10px" align="center" class="titulo-relatorio"> &nbsp;&nbsp; <span class="fa fa-user" aria-hidden="true"> </span>
                                                                                        Dados Pessoais 
                                                                                    </h3>
                                                                                </div>    
                                                                                <div class="col-md-3 pointer arred" id="contato"> 
                                                                                    <h3 style="margin-left:-10px" align="center" class="titulo-relatorio"> &nbsp;&nbsp; <span class="fa fa-phone" aria-hidden="true"> </span>
                                                                                        Contato 
                                                                                    </h3>
                                                                                </div>  
                                                                                <div class="col-md-3 pointer arred" id="institucional"> 
                                                                                    <h3 style="margin-left:-10px" align="center" class="titulo-relatorio"><span class="fa fa-briefcase" aria-hidden="true"> </span>
                                                                                        Institucional 
                                                                                    </h3>
                                                                                </div>  
                                                                                <div class="col-md-3 pointer arred" id="trabalho"> 
                                                                                    <h3 style="margin-left:-10px" align="center" class="titulo-relatorio"> &nbsp;&nbsp; <span class="fa fa-briefcase" aria-hidden="true"> </span>
                                                                                        Dados do Trabalho 
                                                                                    </h3>
                                                                                </div>  
                                                                                <div class="col-md-12">
                                                                                    <hr style="padding-top: 0px; margin-top: 4px !important;">
                                                                                </div>
                                                                            </div>
                                                                            <div id="divPessoais">
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Nome:</b><label style="color:red">*</label>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-7">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success obg" id="nome" name="nome" value="<?= $usuario['nome'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                                <b>CPF:</b><label style="color:red">*</label>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-3">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="11" class="form-control user-success obg" id="cpf" name="cpf" value="<?= $usuario['cpf'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                                <b>RG:</b><label style="color:red">*</label>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-3">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="11" class="form-control user-success obg" id="rg" name="rg" value="<?= $usuario['rg'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Emissor:</b>
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-3">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="20" class="form-control user-success" id="emissor" name="emissor" value="<?= $usuario['orgao_emissor'] ?>">
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>RA:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-3">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="20" class="form-control user-success" id="ra" name="ra" value="<?= $usuario['ra'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>

                                                                                <div class="row">
                                                                                    
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Gênero:</b><label style="color:red">*</label>
                                                                                            </div>                                                                    
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-3">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <select class="form-control user-success obg" id="sexo" name="sexo">
                                                                                                    <option value="" <?= $usuario['genero'] == '' ? 'selected' : '' ?>>Selecionar</option>
                                                                                                    <option value="M" <?= $usuario['genero'] == 'M' ? 'selected' : '' ?>>Masculino</option>
                                                                                                    <option value="F" <?= $usuario['genero'] == 'F' ? 'selected' : '' ?>>Feminino</option>
                                                                                                </select>
                                                                                            </div>                                                                        
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Nascimento:</b><label style="color:red">*</label>
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-3">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="date" maxlength="60" class="form-control user-success obg" id="nascimento" name="nascimento" value="<?= $usuario['data_nascimento'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Civil:</b><label style="color:red">*</label>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-3">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <select class="form-control user-success obg" id="civil" name="civil">
                                                                                                    <option value="" <?= $usuario['estado_civil'] == '' ? 'selected' : '' ?>>Selecionar</option>
                                                                                                    <option value="SOLTEIRO" <?= $usuario['estado_civil'] == 'SOLTEIRO' ? 'selected' : '' ?>>SOLTEIRO</option>
                                                                                                    <option value="CASADO" <?= $usuario['estado_civil'] == 'CASADO' ? 'selected' : '' ?>>CASADO</option>
                                                                                                    <option value="SEPARADO" <?= $usuario['estado_civil'] == 'SEPARADO' ? 'selected' : '' ?>>SEPARADO</option>
                                                                                                    <option value="DIVORCIADO" <?= $usuario['estado_civil'] == 'DIVORCIADO' ? 'selected' : '' ?>>DIVORCIADO</option>
                                                                                                    <option value="VIÚVO" <?= $usuario['estado_civil'] == 'VIÚVO' ? 'selected' : '' ?>>VIÚVO</option>
                                                                                                </select>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Endereço:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-8">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="endereco" name="endereco" value="<?= $usuario['endereco'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Num.:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-2">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="num" name="num" value="<?= $usuario['numero'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Complemento:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="complemento" name="complemento" value="<?= $usuario['complemento'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Bairro:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="bairro" name="bairro" value="<?= $usuario['bairro'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Cidade:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="cidade" name="cidade" value="<?= $usuario['cidade'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Estado:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-2">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <select class="form-control user-success" id="estado" name="estado">
                                                                                                    <option value="" <?= $usuario['estado'] == '' ? 'selected' : '' ?>>Selecionar</option>
                                                                                                    <option value="AC" <?= $usuario['estado'] == 'AC' ? 'selected' : '' ?>>Acre</option>
                                                                                                    <option value="AL" <?= $usuario['estado'] == 'AL' ? 'selected' : '' ?>>Alagoas</option>
                                                                                                    <option value="AP" <?= $usuario['estado'] == 'AP' ? 'selected' : '' ?>>Amapá</option>
                                                                                                    <option value="AM" <?= $usuario['estado'] == 'AM' ? 'selected' : '' ?>>Amazonas</option>
                                                                                                    <option value="BA" <?= $usuario['estado'] == 'BA' ? 'selected' : '' ?>>Bahia</option>
                                                                                                    <option value="CE" <?= $usuario['estado'] == 'CE' ? 'selected' : '' ?>>Ceará</option>
                                                                                                    <option value="DF" <?= $usuario['estado'] == 'DF' ? 'selected' : '' ?>>Distrito Federal</option>
                                                                                                    <option value="ES" <?= $usuario['estado'] == 'ES' ? 'selected' : '' ?>>Espírito Santo</option>
                                                                                                    <option value="GO" <?= $usuario['estado'] == 'GO' ? 'selected' : '' ?>>Goiás</option>
                                                                                                    <option value="MA" <?= $usuario['estado'] == 'MA' ? 'selected' : '' ?>>Maranhão</option>
                                                                                                    <option value="MT" <?= $usuario['estado'] == 'MT' ? 'selected' : '' ?>>Mato Grosso</option>
                                                                                                    <option value="MS" <?= $usuario['estado'] == 'MS' ? 'selected' : '' ?>>Mato Grosso do Sul</option>
                                                                                                    <option value="MG" <?= $usuario['estado'] == 'MG' ? 'selected' : '' ?>>Minas Gerais</option>
                                                                                                    <option value="PA" <?= $usuario['estado'] == 'PA' ? 'selected' : '' ?>>Pará</option>
                                                                                                    <option value="PB" <?= $usuario['estado'] == 'PB' ? 'selected' : '' ?>>Paraíba</option>
                                                                                                    <option value="PR" <?= $usuario['estado'] == 'PR' ? 'selected' : '' ?>>Paraná</option>
                                                                                                    <option value="PE" <?= $usuario['estado'] == 'PE' ? 'selected' : '' ?>>Pernambuco</option>
                                                                                                    <option value="PI" <?= $usuario['estado'] == 'PI' ? 'selected' : '' ?>>Piauí</option>
                                                                                                    <option value="RJ" <?= $usuario['estado'] == 'RJ' ? 'selected' : '' ?>>Rio de Janeiro</option>
                                                                                                    <option value="RN" <?= $usuario['estado'] == 'RN' ? 'selected' : '' ?>>Rio Grande do Norte</option>
                                                                                                    <option value="RS" <?= $usuario['estado'] == 'RS' ? 'selected' : '' ?>>Rio Grande do Sul</option>
                                                                                                    <option value="RO" <?= $usuario['estado'] == 'RO' ? 'selected' : '' ?>>Rondônia</option>
                                                                                                    <option value="RR" <?= $usuario['estado'] == 'RR' ? 'selected' : '' ?>>Roraima</option>
                                                                                                    <option value="SC" <?= $usuario['estado'] == 'SC' ? 'selected' : '' ?>>Santa Catarina</option>
                                                                                                    <option value="SP" <?= $usuario['estado'] == 'SP' ? 'selected' : '' ?>>São Paulo</option>
                                                                                                    <option value="SE" <?= $usuario['estado'] == 'SE' ? 'selected' : '' ?>>Sergipe</option>
                                                                                                    <option value="TO" <?= $usuario['estado'] == 'TO' ? 'selected' : '' ?>>Tocantins</option>
                                                                                                </select>
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>CEP:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-2">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="8" class="form-control user-success" id="cep" name="cep" value="<?= $usuario['cep'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                                <b>Banco:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-2">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <select class="form-control user-success" id="banco" name="banco">
                                                                                                    <option value="" <?= $usuario['num_banco'] == '' ? 'selected' : '' ?>>Selecionar</option>
                                                                                                    <option value="1" <?= $usuario['num_banco'] == '1' ? 'selected' : '' ?>>Banco do Brasil</option>
                                                                                                    <option value="2" <?= $usuario['num_banco'] == '2' ? 'selected' : '' ?>>Bradesco</option>
                                                                                                    <option value="3" <?= $usuario['num_banco'] == '3' ? 'selected' : '' ?>>Caixa Econômica Federal</option>
                                                                                                    <option value="4" <?= $usuario['num_banco'] == '4' ? 'selected' : '' ?>>Itaú</option>
                                                                                                    <option value="5" <?= $usuario['num_banco'] == '5' ? 'selected' : '' ?>>Santander</option>
                                                                                                    <option value="6" <?= $usuario['num_banco'] == '6' ? 'selected' : '' ?>>Sicred</option>
                                                                                                </select>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Agência:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-2">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="agencia" name="agencia" value="<?= $usuario['num_agencia'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                                <b>Conta:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="conta" maxlength="80" name="conta" value="<?= $usuario['num_conta'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>

                                                                                </div>
                                                                            </div>
                                                                            <div id="divContato"> 
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Fixo:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row text">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="fixo" name="fixo" value="<?= $usuario['fixo'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Celular:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="celular" name="celular" value="<?= $usuario['celular'] ?>">
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>E-mail 1:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row text">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" readonly id="email1" name="email1" value="<?= $usuario['email'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>E-mail 2:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="email2" name="email2" value="<?= $usuario['email2'] ?>">
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Facebook:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row text">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="facebook" name="facebook" value="<?= $usuario['facebook'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Skype:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row text">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="skype" name="skype" value="<?= $usuario['skype'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Lattes:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row text">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="lattes" name="lattes" value="<?= $usuario['lattes'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                            </div>

                                                                            <div id="divInstitucional">                   
                                                                                <div class="row">
                                                                                    <div class="col-md-2">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Nome do Curso Atual:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-10">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="curso_nome" name="curso_nome" value="<?= $usuario['curso_atual_nome'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-2">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                                <b>Escolaridade:</b>
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-3">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <select class="form-control user-success" id="escolaridade" name="escolaridade">
                                                                                                    <option value="" <?= $usuario['nivel_escolaridade_fk'] == 0 ? 'selected' : '' ?>>Selecionar</option>
                                                                                                    <?php foreach ($escolaridades as $dados): ?>
                                                                                                        <option value="<?= $dados['cod_nivel'] ?> <?= $usuario['nivel_escolaridade_fk'] == $dados['cod_nivel'] ? 'selected' : '' ?>" ><?= $dados['descricao'] ?></option>
                                                                                                    <?php endforeach; ?>
                                                                                                </select>
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                                <b>Série:</b>
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-3">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="curso_atual_serie" name="curso_atual_serie" value="<?= $usuario['curso_atual_serie'] ?>">
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Período:</b>
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-2">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="curso_periodo" name="curso_periodo" value="<?= $usuario['curso_periodo'] ?>">
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-2">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Curso de Graduação:</b>
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-10">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="graduacao_nome" name="graduacao_nome" value="<?= $usuario['graduacao_nome'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-2">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                                <b>Instituição de Graduação:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-7">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="graduacao_instituicao" name="graduacao_instituicao" value="<?= $usuario['graduacao_instituicao'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Ano:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-2">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="graduacao_ano_conclusao" name="graduacao_ano_conclusao" value="<?= $usuario['graduacao_ano_conclusao'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-2">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Curso de Pós-Graduação:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-10">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="pos_graduacao_nome" name="pos_graduacao_nome" value="<?= $usuario['pos_graduacao_nome'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-2">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                                <b>Instituição de Pós-Graduação:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-7">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="pos_graduacao_instituicao" name="pos_graduacao_instituicao" value="<?= $usuario['pos_graduacao_instituicao'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Ano:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-2">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="pos_graduacao_ano" name="pos_graduacao_ano" value="<?= $usuario['pos_graduacao_ano'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-2">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Curso de Mestrado:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-10">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="mestrado_nome" name="mestrado_nome" value="<?= $usuario['mestrado_nome'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-2">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                                <b>Instituição de Mestrado:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-7">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="mestrado_instituicao" name="mestrado_instituicao" value="<?= $usuario['mestrado_instituicao'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Ano:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-2">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="mestrado_ano" name="mestrado_ano" value="<?= $usuario['mestrado_ano'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-2">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Curso de Doutorado:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-10">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="doutorado_nome" name="doutorado_nome" value="<?= $usuario['doutorado_nome'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-2">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                                <b>Instituição:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-7">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="doutorado_instituicao" name="doutorado_instituicao" value="<?= $usuario['doutorado_instituicao'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Ano:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-2">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="doutorado_ano" name="doutorado_ano" value="<?= $usuario['doutorado_ano'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div id="divTrabalho"> 
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Empresa:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-11">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="emp_nome" name="emp_nome" value="<?= $usuario['emp_nome'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Endereço:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-7">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="emp_endereco" name="emp_endereco" value="<?= $usuario['emp_endereco'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Num.:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-3">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="emp_numero" name="emp_numero" value="<?= $usuario['emp_numero'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Complemento:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="emp_complemento" name="emp_complemento" value="<?= $usuario['emp_complemento'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Bairro:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="emp_bairro" name="emp_bairro" value="<?= $usuario['emp_bairro'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Cidade:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="emp_cidade" name="emp_cidade" value="<?= $usuario['emp_cidade'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Estado:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <select class="form-control user-success" id="emp_estado" name="emp_estado">
                                                                                                    <option value="" <?= $usuario['estado'] == '' ? 'selected' : '' ?>>Selecionar</option>
                                                                                                    <option value="AC" <?= $usuario['estado'] == 'AC' ? 'selected' : '' ?>>Acre</option>
                                                                                                    <option value="AL" <?= $usuario['estado'] == 'AL' ? 'selected' : '' ?>>Alagoas</option>
                                                                                                    <option value="AP" <?= $usuario['estado'] == 'AP' ? 'selected' : '' ?>>Amapá</option>
                                                                                                    <option value="AM" <?= $usuario['estado'] == 'AM' ? 'selected' : '' ?>>Amazonas</option>
                                                                                                    <option value="BA" <?= $usuario['estado'] == 'BA' ? 'selected' : '' ?>>Bahia</option>
                                                                                                    <option value="CE" <?= $usuario['estado'] == 'CE' ? 'selected' : '' ?>>Ceará</option>
                                                                                                    <option value="DF" <?= $usuario['estado'] == 'DF' ? 'selected' : '' ?>>Distrito Federal</option>
                                                                                                    <option value="ES" <?= $usuario['estado'] == 'ES' ? 'selected' : '' ?>>Espírito Santo</option>
                                                                                                    <option value="GO" <?= $usuario['estado'] == 'GO' ? 'selected' : '' ?>>Goiás</option>
                                                                                                    <option value="MA" <?= $usuario['estado'] == 'MA' ? 'selected' : '' ?>>Maranhão</option>
                                                                                                    <option value="MT" <?= $usuario['estado'] == 'MT' ? 'selected' : '' ?>>Mato Grosso</option>
                                                                                                    <option value="MS" <?= $usuario['estado'] == 'MS' ? 'selected' : '' ?>>Mato Grosso do Sul</option>
                                                                                                    <option value="MG" <?= $usuario['estado'] == 'MG' ? 'selected' : '' ?>>Minas Gerais</option>
                                                                                                    <option value="PA" <?= $usuario['estado'] == 'PA' ? 'selected' : '' ?>>Pará</option>
                                                                                                    <option value="PB" <?= $usuario['estado'] == 'PB' ? 'selected' : '' ?>>Paraíba</option>
                                                                                                    <option value="PR" <?= $usuario['estado'] == 'PR' ? 'selected' : '' ?>>Paraná</option>
                                                                                                    <option value="PE" <?= $usuario['estado'] == 'PE' ? 'selected' : '' ?>>Pernambuco</option>
                                                                                                    <option value="PI" <?= $usuario['estado'] == 'PI' ? 'selected' : '' ?>>Piauí</option>
                                                                                                    <option value="RJ" <?= $usuario['estado'] == 'RJ' ? 'selected' : '' ?>>Rio de Janeiro</option>
                                                                                                    <option value="RN" <?= $usuario['estado'] == 'RN' ? 'selected' : '' ?>>Rio Grande do Norte</option>
                                                                                                    <option value="RS" <?= $usuario['estado'] == 'RS' ? 'selected' : '' ?>>Rio Grande do Sul</option>
                                                                                                    <option value="RO" <?= $usuario['estado'] == 'RO' ? 'selected' : '' ?>>Rondônia</option>
                                                                                                    <option value="RR" <?= $usuario['estado'] == 'RR' ? 'selected' : '' ?>>Roraima</option>
                                                                                                    <option value="SC" <?= $usuario['estado'] == 'SC' ? 'selected' : '' ?>>Santa Catarina</option>
                                                                                                    <option value="SP" <?= $usuario['estado'] == 'SP' ? 'selected' : '' ?>>São Paulo</option>
                                                                                                    <option value="SE" <?= $usuario['estado'] == 'SE' ? 'selected' : '' ?>>Sergipe</option>
                                                                                                    <option value="TO" <?= $usuario['estado'] == 'TO' ? 'selected' : '' ?>>Tocantins</option>
                                                                                                </select>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>CEP:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-3">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="emp_cep" name="emp_cep" value="<?= $usuario['emp_cep'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    
                                                                                </div>
                                                                                <div class="row">
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Fixo:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row text">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="emp_telefone" name="emp_telefone" value="<?= $usuario['emp_telefone'] ?>">
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-1">
                                                                                        <div class="row text-right">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <b>Celular:</b>
                                                                                            </div> 

                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="col-md-5">
                                                                                        <div class="row">     
                                                                                            <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                                <input type="text" maxlength="60" class="form-control user-success" id="emp_celular" name="emp_celular" value="<?= $usuario['emp_celular'] ?>">
                                                                                            </div> 
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row" style="margin:30px">
                                                                                <div class="col-md-12 col-xs-12 text-center">
                                                                                    <button type="button" class="btn btn-primary3 btn-min" style="width:170px" id="btnEnviar" name="btnEnviar">
                                                                                        <b>Alterar&nbsp;&nbsp;<i class="fa fa-edit"></i></b>
                                                                                    </button>
                                                                                </div>
                                                                            </div>
                                                                        </form>
                                                                    </div>  
                                                                </div>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>  
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $("#divContato").hide();
        $("#divInstitucional").hide();
        $("#divTrabalho").hide();

        $("#btnEnviar").click(function () {

            var data = {};
            $.each($("#frmDados .obg").serializeArray(), function (_, field) {
                data[field.name] = field.value;
            });
            
            if (!validaParametros(data)) {
                Swal.fire({
                    title: 'Atenção!',
                    html: "Digite todos os campos obrigatórios (*)",
                    type: 'info'
                });
                return false;
            }
            
            if(!validarData(data.nascimento)){
            Swal.fire({
                title: 'Atenção!',
                html: "A data de nascimento não é válida.",
                type: 'info'
            });
            return false;
        }

            var options = {
                url: '/alterar-dados',
                type: 'POST',
                dataType: 'json',
                cache: false,
                success: function (retorno) {
                    if (retorno.response) {
                        Swal.fire({
                            title: 'Sucesso!',
                            html: retorno.msg,
                            type: 'success',
                            onClose: () => {
                                window.location.reload();
                            }
                        });

                    }else{
                        Swal.fire({
                            title: 'Atenção!',
                            html: retorno.msg,
                            type: 'warning'
                        });
                    }
                }
            };

        $('#frmDados').ajaxSubmit(options);
            
        });
    });
        $("#contato").on('click', function () {
        $("div").removeClass('selected');
        $(this).addClass('selected');
        $("#divContato").show();
        $("#divPessoais").hide();
        $("#divInstitucional").hide();
        $("#divTrabalho").hide();
    });
    $("#institucional").on('click', function () {
        $("div").removeClass('selected');
        $(this).addClass('selected');
        $("#divInstitucional").show();
        $("#divPessoais").hide();
        $("#divContato").hide();
        $("#divTrabalho").hide();
    });
    $("#trabalho").on('click', function () {
        $("div").removeClass('selected');
        $(this).addClass('selected');
        $("#divTrabalho").show();
        $("#divPessoais").hide();
        $("#divInstitucional").hide();
        $("#divContato").hide();
    });
    $("#pessoais").on('click', function () {
        $("div").removeClass('selected');
        $(this).addClass('selected');
        $("#divPessoais").show();
        $("#divContato").hide();
        $("#divInstitucional").hide();
        $("#divTrabalho").hide();
    });

</script>