<style>
    .selected{
        background-color: #dceaef;
        border-bottom: 3px solid #a4c2cc;
    }
    .arred{
        border-radius: 5px;
        line-height: 70px;
    }
    .image{
        width: 40% !important;
    }
</style>
<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix mt">            
                <div class="container pd-0">
                    <div class="row">
                        <div class="col-md-12 pd-0" >
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary2 panels"><i class="fa fa-user"></i>&nbsp;<label class="title">Perfil</label></div>
                                    <div class="info" style="height:800px; padding:30px">
                                        <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12 pd-0">                    
                                            <div class="new-color-1 border-new-color-1"> 
                                                <b class="cinza-escuro">&nbsp;</b>
                                            </div> 
                                            <div class="table-responsive">
                                                <table class="table table-striped table-bordered" >    
                                                    <tr class="font-min">
                                                        <td align="left">
                                                            <div class="widget-body" style="padding-left:30px; padding-right:30px">
                                                                <div class="widget-main">
                                                                    <div class="row" id="dvCadastro"> 
                                                                        <div class="row" style="margin:20px"> 
                                                                            <div class="col-md-3 selected pointer arred" id="pessoais"> 
                                                                                <h2 style="margin-left:-10px" align="center" class="titulo-relatorio"> &nbsp;&nbsp; <span class="fa fa-user" aria-hidden="true"> </span>
                                                                                    Dados Pessoais 
                                                                                </h2>
                                                                            </div>    
                                                                            <div class="col-md-3 pointer arred" id="contato"> 
                                                                                <h2 style="margin-left:-10px" align="center" class="titulo-relatorio"> &nbsp;&nbsp; <span class="fa fa-phone" aria-hidden="true"> </span>
                                                                                    Contato 
                                                                                </h2>
                                                                            </div>  
                                                                            <div class="col-md-3 pointer arred" id="institucional"> 
                                                                                <h2 style="margin-left:-10px" align="center" class="titulo-relatorio"><span class="fa fa-briefcase" aria-hidden="true"> </span>
                                                                                    Institucional 
                                                                                </h2>
                                                                            </div>  
                                                                            <div class="col-md-3 pointer arred" id="trabalho"> 
                                                                                <h2 style="margin-left:-10px" align="center" class="titulo-relatorio"> &nbsp;&nbsp; <span class="fa fa-briefcase" aria-hidden="true"> </span>
                                                                                    Dados do Trabalho 
                                                                                </h2>
                                                                            </div>  
                                                                            <div class="col-md-12">
                                                                                <hr style="padding-top: 0px; margin-top: 4px !important;">
                                                                            </div>
                                                                        </div>
                                                                        <div id="divPessoais">
                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Nome:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-11">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="nome" name="nome" value="Vivangola Perez da Silva Cardoso">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                            <b>CPF:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-3">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="cpf" name="cpf" value="123.456.789-10">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                            <b>RG:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-3">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="rg" name="rg" value="12.456.789-0">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>RA:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-3">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="ra" name="ra" value="0210481683013">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>

                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Sexo:</b>
                                                                                        </div>                                                                    
                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-3">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <select readonly class="form-control user-success" id="sexo" name="sexo">
                                                                                                <option value="M" selected>Masculino</option>
                                                                                                <option value="F" >Feminino</option>
                                                                                            </select>
                                                                                        </div>                                                                        
                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Idade:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-3">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="idade" name="idade" value="22">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Civil:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-3">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <select readonly class="form-control user-success" id="civil" name="civil">
                                                                                                <option value="1">Viúvo</option>
                                                                                            </select>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Endereço:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-7">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="endereco" name="endereco" value="Rua da Minha Casa Onde Eu Moro">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Num.:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-3">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="num" name="num" value="53105">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Bairro:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="bairro" name="bairro" value="Vila do Mapão">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Cidade:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="cidade" name="cidade" value="Ipaussu">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">

                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Estado:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <select readonly class="form-control user-success" style=" width: 75px;" id="estado" name="estado">
                                                                                                <option value="SP">SP</option>
                                                                                            </select>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>CEP:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-3">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="cep" name="cep" value="18950-000">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-2">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Complemento:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-4">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="cep" name="cep" value="Casa">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                            <b>Banco:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-2">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="escolaridade" name="escolaridade" value="230">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Agência:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-2">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="periodo" name="periodo" value="2020">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                            <b>Conta:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="serie" name="serie" value="123564-8">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>

                                                                            </div>
                                                                        </div>
                                                                        <div id="divContato"> 
                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Fixo:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row text">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="fixo" name="fixo" value="(14) 3344-1526">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Celular:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="celular" name="celular" value="(14) 99782-8864">
                                                                                        </div> 
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>E-mail 1:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row text">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="email" name="email" value="vivangola100%jesus@hotmail.com">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>E-mail 2:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="telefone" name="telefone" value="vivangola100%jesus@hotmail.com">
                                                                                        </div> 
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Facebook:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row text">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="email" name="email" value="vivangola100%jesus@hotmail.com">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Skype:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row text">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="email" name="email" value="vivangola100%jesus@hotmail.com">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Lattes:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row text">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="email" name="email" value="vivangola100%jesus@hotmail.com">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>

                                                                        <div id="divInstitucional">                   
                                                                            <div class="row">
                                                                                <div class="col-md-2">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Nome do Curso:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-10">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="curso" name="curso" value="Tecnólogo em Análise e Desenvolvimento de Sistemas">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-2">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                            <b>Escolaridade:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-3">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="escolaridade" name="escolaridade" value="Graduação">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                            <b>Serie:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-3">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="serie" name="serie" value="6° Semestre">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Período:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-2">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="periodo" name="periodo" value="Noturno">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-2">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Curso de Graduação:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-10">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="curso" name="curso" value="Tecnólogo em Análise e Desenvolvimento de Sistemas">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-2">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                            <b>Instituição:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-7">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="escolaridade" name="escolaridade" value="FATEC Ourinhos">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Ano:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-2">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="periodo" name="periodo" value="2019">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-2">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Curso de Mestrado:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-10">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="curso" name="curso" value="Tecnólogo em Análise e Desenvolvimento de Sistemas">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-2">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                            <b>Instituição:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-7">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="escolaridade" name="escolaridade" value="FATEC Ourinhos">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Ano:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-2">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="periodo" name="periodo" value="2019">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-2">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Curso de Doutorado:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-10">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="curso" name="curso" value="Tecnólogo em Análise e Desenvolvimento de Sistemas">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-2">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12 ">
                                                                                            <b>Instituição:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-7">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="escolaridade" name="escolaridade" value="FATEC Ourinhos">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Ano:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-2">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="periodo" name="periodo" value="2019">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div id="divTrabalho"> 
                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Empresa:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-11">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="nome" name="nome" value="Vivangola Perez da Silva Cardoso">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Endereço:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-7">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="endereco" name="endereco" value="Rua da Minha Casa Onde Eu Moro">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Num.:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-3">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="num" name="num" value="53105">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Bairro:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="bairro" name="bairro" value="Vila do Mapão">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Cidade:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="cidade" name="cidade" value="Ipaussu">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">

                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Estado:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <select readonly class="form-control user-success" style=" width: 75px;" id="estado" name="estado">
                                                                                                <option value="SP">SP</option>
                                                                                            </select>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>CEP:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-3">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="cep" name="cep" value="18950-000">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-2">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Complemento:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-4">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="cep" name="cep" value="Casa">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                            <div class="row">
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Fixo:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row text">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="fixo" name="fixo" value="(14) 3344-1526">
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-1">
                                                                                    <div class="row text-right">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <b>Celular:</b>
                                                                                        </div> 

                                                                                    </div>
                                                                                </div>
                                                                                <div class="col-md-5">
                                                                                    <div class="row">     
                                                                                        <div class="form-group col-xs-12 col-sm-12 col-md-12">
                                                                                            <input readonly type="text" maxlength="60" class="form-control user-success" id="celular" name="celular" value="(14) 99782-8864">
                                                                                        </div> 
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="row" style="margin:30px">
                                                                            <div class="col-md-12 col-xs-12 text-center">
                                                                                <button type="submit" class="btn btn-primary3 btn-min" style="width:170px" id="btnEnviar" name="btnEnviar">
                                                                                    <b>Alterar&nbsp;&nbsp;<i class="fa fa-edit"></i></b>
                                                                                </button>
                                                                            </div>
                                                                        </div>
                                                                    </div>  
                                                                </div>
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </div>  
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </div>  
                                                            </div>
                                                            </div>
                                                            </div>
                                                            </div>

                                                            <script type="text/javascript">

                                                                $(document).ready(function () {
                                                                    $("#divContato").hide();
                                                                    $("#divInstitucional").hide();
                                                                    $("#divTrabalho").hide();
                                                                });

                                                                $("#contato").on('click', function () {
                                                                    $("div").removeClass('selected');
                                                                    $(this).addClass('selected');
                                                                    $("#divContato").show();
                                                                    $("#divPessoais").hide();
                                                                    $("#divInstitucional").hide();
                                                                    $("#divTrabalho").hide();
                                                                });
                                                                $("#institucional").on('click', function () {
                                                                    $("div").removeClass('selected');
                                                                    $(this).addClass('selected');
                                                                    $("#divInstitucional").show();
                                                                    $("#divPessoais").hide();
                                                                    $("#divContato").hide();
                                                                    $("#divTrabalho").hide();
                                                                });
                                                                $("#trabalho").on('click', function () {
                                                                    $("div").removeClass('selected');
                                                                    $(this).addClass('selected');
                                                                    $("#divTrabalho").show();
                                                                    $("#divPessoais").hide();
                                                                    $("#divInstitucional").hide();
                                                                    $("#divContato").hide();
                                                                });
                                                                $("#pessoais").on('click', function () {
                                                                    $("div").removeClass('selected');
                                                                    $(this).addClass('selected');
                                                                    $("#divPessoais").show();
                                                                    $("#divContato").hide();
                                                                    $("#divInstitucional").hide();
                                                                    $("#divTrabalho").hide();
                                                                });

                                                            </script>