<script src="//cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>
<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt">            
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-book"></i>&nbsp;<label class="title">Emails Enviados</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 10px;padding-right: 10px;margin-top: 10px;margin-bottom: 20px;">
                                            <form action="/email" method="post" enctype="">
                                                <div class="col-md-6 col-sm-4 col-xs-8">
                                                    <input type="text" name="pesquisa" placeholder="Pesquisar" class="form-control" value="<?= $pesq != '' ? $pesq : '' ?>">
                                                </div>  
                                                <div class="col-md-2 col-sm-2 col-xs-4">
                                                    <select class="form-control" name="filtros">
                                                        <option value="-1">Todos</option>
                                                        <option value="1" <?= $filtro == '1' ? 'selected' : '' ?>>Assunto</option>
                                                        <option value="2" <?= $filtro == '2' ? 'selected' : '' ?>>E-mail</option>
                                                       
                                                     </select>
                                                </div>
                                                <div class="col-md-2 col-sm-3 col-xs-6">
                                                    <button class="btn btn-primary-borded2 form-control" type="submit">
                                                        Pesquisar&nbsp;
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                </div>
                                                <div class="col-md-2 col-sm-3 col-xs-6">
                                                    <button class="btn btn-primary-borded2 form-control" type="button" onClick="showAdd()">
                                                        Novo&nbsp;
                                                        <i class="fa fa-plus"></i>
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="table-responsive" style="margin-top: 10px;">
                                            <?php
                                            $relatorio->gerarCabecalho(12);
                                            if (!empty($result)) {
                                                foreach ($result as $dados) {
                                                    $relatorio->definirVariavel('1', "<button type='button' class='btn btn-primary4' style='width:100%' onClick=showEdit('".$dados['cod_email']."')><i class='pointer fa fa-eye'></i></button>");
                                                    $relatorio->gerarRelatorio($dados);
                                                }
                                            }
                                            $relatorio->gerarRodape();
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalAdd" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title color-primary2"><i class="fa fa-plus"></i>&nbsp;Enviar E-mail</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="formAdd" action="/email/add" method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="add_emails" class="col-form-label">Para:</label><label style="color:red">*</label>&nbsp;<label style="color:gray"></label>
                        <input type="text"  class="form-control" id="add_emails" name="add_emails" placeholder="ex: email@hotmail.com, email2@gmail.com">
                    </div>
                    <div class="form-group">
                        <label for="add_assunto" class="col-form-label">Assunto:</label><label style="color:red">*</label>
                        <input type="text"  class="form-control" id="add_assunto" name="add_assunto">
                    </div>
                    <div class="form-group">
                        <label for="add_texto" class="col-form-label">Texto:</label><label style="color:red">*</label>
                        <textarea id="add_texto" name="add_texto" style="width: 100%; height: 100px;"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary-borded2" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary3" onclick="add()">Enviar <i class="fa fa-check"></i></button>
                </div>
            </form>
        </div>
    </div>
</div>


<div class="modal fade" id="modalEdit" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title color-primary2"><i class="fa fa-plus"></i>&nbsp;Visualizar E-mail</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="formEdit" method="post">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="edit_emails" class="col-form-label">Para:</label><label style="color:red">*</label>&nbsp;<label style="color:gray"></label>
                        <input type="text" readonly  class="form-control" id="edit_emails" name="edit_emails" placeholder="ex: email@hotmail.com, email2@gmail.com">
                    </div>
                    <div class="form-group">
                        <label for="edit_assunto" class="col-form-label">Assunto:</label><label style="color:red">*</label>
                        <input type="text" readonly  class="form-control" id="edit_assunto" name="edit_assunto">
                    </div>
                    <div class="form-group">
                        <label for="edit_texto" class="col-form-label">Texto:</label><label style="color:red">*</label>
                        <textarea id="edit_texto" readonly name="edit_texto" style="width: 100%; height: 100px;"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary-borded2" data-dismiss="modal">Cancelar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    
    window.onload = function()  {
        CKEDITOR.replace('add_texto');
        CKEDITOR.replace('edit_texto');
    };

    $(document).ready(function () {
        $('#relatorio').DataTable({
            "language": {
                "url": "js/datatable/pt-br.json"
            },
            "pageLength": 10, 
            "ordering": false,
            "lengthChange": false,
            "searching": false,
        });
    });
    
    function showAdd(){
        $('#modalAdd').modal('show');
    }
    
    function add(){
        
        for (instance in CKEDITOR.instances) {
            CKEDITOR.instances[instance].updateElement();
        }
        
        var data = {};
        $.each($("#formAdd").serializeArray(), function (_, field) {
            data[field.name] = field.value;
        });
        
        if(!validaParametros(data)){
            Swal.fire({
                title: 'Atenção!',
                html: "Digite todos os campos obrigatórios (*)",
                type: 'info'
            });
            return false;
        }
        
        var options = {
            url: '/email/add',
            type: 'POST',
            dataType: 'json',
            cache: false,
            success: function (retorno) {
                if (retorno.response) {
                    Swal.fire({
                        title: 'Sucesso!',
                        html: retorno.msg,
                        type: 'success',
                        onClose: () => {
                            window.location.reload();
                        }
                    });
                        
                }else{
                    Swal.fire({
                        title: 'Atenção!',
                        html: retorno.msg,
                        type: 'warning'
                    });
                }
            }
        };
        loader();
        $('#formAdd').ajaxSubmit(options);
    }
    
    
    function showEdit(cod){
        $.ajax({
            url: '/email/showEdit',
            data: {cod : cod},
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = JSON.parse(retorno);
                Swal.close();
                if(retorno.response){
                    $('#edit_emails').val(retorno.result['email_destinatario']);
                    $('#edit_assunto').val(retorno.result['assunto']);
                    CKEDITOR.instances['edit_texto'].setData(retorno.result['texto']); 
                    $('#modalEdit').modal('show');
                }else{
                    Swal.fire({
                        title: 'Atenção!',
                        html: 'E-mail não encontrado!',
                        type: 'info'
                    });
                }
            }
        });
    }
        
    function showDelete(cod){
        Swal.fire({
            title: 'Atenção!',
            html: 'Deseja realmente excluir?',
            type: 'info',
            showCancelButton: true,
            preConfirm: () => {
                $.ajax({
                    url: '/email/delete',
                    data: {cod : cod},
                    type: 'json',
                    method: 'POST',
                    beforeSend: function () {
                        loader();
                    },
                    success: function (retorno) {
                        Swal.fire({
                            title: 'Sucesso!',
                            html: 'Material deletado.',
                            type: 'success',
                            onClose: () => {
                                window.location.reload();
                            }
                        });
                    }
                });
            }
        });
    }

</script>