<?= $this->doctype() ?>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-155099311-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-155099311-1');
</script>


<html lang="en">
    <head>
        <?php
            header("Cache-Control: no-cache, must-revalidate");
        ?>
        
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        
        <?= $this->headTitle('GRUPO EDACI')->setSeparator(' - ')->setAutoEscape(false) ?>
        
        <meta name="description" content="O Grupo de Pesquisa Educação e Acidentes (EDACI) da UNESP Marília, tem como função produzir estudos e intervenções educativas para prevenção de acidentes e promoção da segurança.">        
        <meta property="og:image" content="/img/logo/logo_branco.png">
        <meta property="og:image:type" content="image/png">
        <meta property="og:image:width" content="249">
        <meta property="og:image:height" content="149">

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/logo/favicon.png'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/theme_styles.min.css'))
        
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/nanoscroller.min.css'))
            ->prependStylesheet($this->basePath('css/sweetalert.css'))
            ->prependStylesheet($this->basePath('css/login.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/funcoes.js'))
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->prependFile($this->basePath('js/sweetalert.min.js'))
            ->prependFile($this->basePath('js/material.js'))
        ?>
    </head>
    
    
    <body>
        <div>
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>


<script type="text/javascript">
    function loader(){
        Swal.fire({
            title: '',
            html: '',
            onBeforeOpen: () => {
              Swal.showLoading();
            }
        });
    }
</script>