<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt" style="margin-top: 2px !important;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-users"></i>&nbsp;<label class="title">Membros</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 10px;padding-right: 10px;margin-top: 10px;margin-bottom: 20px;">
                                            <form action="/usuarios/membros" method="post" enctype="">
                                                <div class="col-md-6 col-sm-4 col-xs-8">
                                                    <input type="text" name="pesquisa" placeholder="Pesquisar" class="form-control" value="<?= $pesq != '' ? $pesq : '' ?>">
                                                </div>  
                                                <div class="col-md-2 col-sm-2 col-xs-4">
                                                    <select class="form-control" name="filtros">
                                                        <option value="-1" <?= $filtro == '-1' ? 'selected' : '' ?>>Todos</option>
                                                        <option value="1" <?= $filtro == '1' ? 'selected' : '' ?>>Nome</option>
                                                        <option value="2" <?= $filtro == '2' ? 'selected' : '' ?>>Nível de Escolaridade</option>
                                                    </select>
                                                </div>
                                                <div class="col-md-2 col-sm-3 col-xs-6">
                                                    <button class="btn btn-primary-borded2 form-control" type="submit">
                                                        Pesquisar&nbsp;
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                </div>
                                                <div class="col-md-2 col-sm-3 col-xs-6">
                                                    <button class="btn btn-primary-borded2 form-control" type="button" onClick="showAdd()">
                                                        Novo&nbsp;
                                                        <i class="fa fa-plus"></i>
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="table-responsive" style="margin-top: 10px;">
                                            <?php
                                            $relatorio->gerarCabecalho(12);
                                            if ($membros) {
                                                foreach ($membros as $dados) {
                                                    
                                                    $relatorio->definirVariavel('0', '<img style="height:80px;width:80px" src="/arquivos/perfil/foto-perfil-' . $dados['cod'] . '.jpg" onerror=$(this).attr("src","/img/semfoto.png")>');
                                                    
                                                    if($dados['ativo'] == 1){
                                                        
                                                    }
                                                    
                                                    if($dados['pre_cadastro'] == '0'){
                                                        $relatorio->definirVariavel('2', "<button type='button' class='btn btn-primary4' style='width:100%;margin-bottom:2px' onClick=aceitar('".$dados['cod']."','1')>ACEITAR <i class='pointer fa fa-check'></i></button>".
                                                                                         "<button type='button' class='btn btn-primary4' style='width:100%' onClick=aceitar('".$dados['cod']."','2')>RECUSAR <i class='pointer fa fa-times'></i></button>");
                                                        $relatorio->definirVariavel('1', "");
                                                    }else if($dados['pre_cadastro'] == '1'){
                                                        if($dados['adm'] == '1'){
                                                            $relatorio->definirVariavel('2', "<font style='color:#629bad'>Pré-cadastrado pelo Administrador</font>");
                                                        }else{
                                                            $relatorio->definirVariavel('2', "<font style='color:#629bad'>Aceito <i class='pointer fa fa-check'></i></font>");
                                                        }
                                                        if($dados['ativo'] == "0"){
                                                            $relatorio->definirVariavel('1', '<div class="switch_box box_1"><input type="checkbox" class="switch_1" id="alterar_status" onchange=ativar("'.$dados['cod'].'",this) name="alterar_status"></div>');
                                                        }else{
                                                            $relatorio->definirVariavel('1', '<div class="switch_box box_1"><input type="checkbox" class="switch_1" id="alterar_status" onchange=ativar("'.$dados['cod'].'",this) name="alterar_status" checked></div>');
                                                        }
                                                        
                                                    }else if($dados['pre_cadastro'] == '2'){
                                                        $relatorio->definirVariavel('2', "<font style='color:#629bad'>Recusado <i class='pointer fa fa-times'></i></font>");
                                                        $relatorio->definirVariavel('1', "");
                                                    }
                                                    
                                                    ///$relatorio->definirVariavel('2', "<button type='button' class='btn btn-primary4' style='width:100%' onClick=showDelete('".$dados['cod_aviso']."')><i class='pointer fa fa-times'></i></button>");
                                                    //$relatorio->definirLink('1', "/eventos?codigo=" . $dados['evento']);

                                                    //chamada para imprimir o relatorio linha a linha 
                                                    //passando as linhas do resultSet como parametro               
                                                    $relatorio->gerarRelatorio($dados);
                                                }
                                            }
                                            $relatorio->gerarRodape();
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#tabela').DataTable({
            "language": {
                "url": "js/datatable/pt-br.json"
            },
            "columnDefs": [ { "orderable": false, "targets": [5,6] }],
            "lengthChange": false,
            "searching": false
        });
    });
    
    function showAdd(){
        $('#modalAdd').modal('show');
    }
    
    function aceitar(usuario,aceitar){
        
        Swal.fire({
            title: 'Atenção!',
            html: aceitar == 1 ? 'Deseja realmente <b>aceitar</b> esse Pré-Cadastro?' : 'Deseja realmente <b>recusar</b> esse Pré-Cadastro?' , 
            type: 'info',
            showCancelButton: true,
            preConfirm: () => {
                $.ajax({
                    url: '/usuarios/aceitar',
                    data: {
                        aceitar     : aceitar,
                        cod_usuario : usuario
                    },
                    type: 'json',
                    method: 'POST',
                    beforeSend: function () {
                        loader();
                    },
                    success: function (retorno) {
                        retorno = JSON.parse(retorno);
                        Swal.fire({
                            title: 'Sucesso!',
                            html: retorno['msg'],
                            type: 'success',
                            onClose: () => {
                                loader();
                                window.location.reload();
                            }
                        });
                    }
                });
            }
        });
    }
    
    function ativar(usuario,element){
        var ativo = $(element).is(':checked') ? 1 : 0;
        
        $.ajax({
            url: '/usuarios/ativar',
            data: {
                cod_usuario : usuario,
                ativar      : ativo
            },
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                Swal.close();
            }
        });
        
    }
    
    
    function showEdit(cod){
        $.ajax({
            url: '/avisos/showEdit',
            data: {cod_aviso : cod},
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = JSON.parse(retorno);
                Swal.close();
                if(retorno.response){
                    
                    $('#edit_cod').val(retorno.result['cod_aviso']);
                    $('#edit_assunto').val(retorno.result['aviso_assunto']);
                    $('#edit_desc').val(retorno.result['aviso_desc']);
                    $('#edit_escolaridade option[value="'+retorno.result['cod_nivel']+'"]').attr('selected','true');
                    $('#edit_dtini').val(retorno.result['date_ini']);
                    $('#edit_dtfim').val(retorno.result['date_fim']);
                    $('#edit_hini').val(retorno.result['inicio_hora']);
                    $('#edit_hfim').val(retorno.result['fim_hora']);
                    
                    $('#modalEdit').modal('show');
                }else{
                    Swal.fire({
                        title: 'Atenção!',
                        html: 'Aviso não encontrado.',
                        type: 'info'
                    });
                }
            }
        });
    }
    
    function edit(){
        
        var data = {
            cod                  : $('#edit_cod').val(),
            edit_assunto         : $('#edit_assunto').val(),
            edit_desc            : $('#edit_desc').val(),
            edit_escolaridade    : $('#edit_escolaridade').val(),
            edit_dtini           : $('#edit_dtini').val(),
            edit_dtfim           : $('#edit_dtfim').val(),
            edit_hini            : $('#edit_hini').val(),
            edit_hfim            : $('#edit_hfim').val()
        };
        
        if(validaParametros(data)){
            $.ajax({
                url: '/avisos/edit',
                data: data,
                type: 'json',
                method: 'POST',
                beforeSend: function () {
                    loader();
                },
                success: function (retorno) {
                    Swal.fire({
                        title: 'Sucesso!',
                        html: 'Aviso editado com sucesso.',
                        type: 'success',
                        onClose: () => {
                            window.location.reload();
                        }
                    });
                },
            });
        }
    }
    
    function showDelete(cod){
        Swal.fire({
            title: 'Atenção!',
            html: 'Deseja realmente excluir?',
            type: 'info',
            showCancelButton: true,
            preConfirm: () => {
                $.ajax({
                    url: '/avisos/delete',
                    data: {cod_aviso : cod},
                    type: 'json',
                    method: 'POST',
                    beforeSend: function () {
                        loader();
                    },
                    success: function (retorno) {
                        Swal.fire({
                            title: 'Sucesso!',
                            html: 'Aviso deletado.',
                            type: 'success',
                            onClose: () => {
                                window.location.reload();
                            }
                        });
                    }
                });
            }
        });
    }

</script>