<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt">            
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-book"></i>&nbsp;<label class="title">Assuntos</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 10px;padding-right: 10px;margin-top: 10px;margin-bottom: 20px;">
                                            <form action="/assunto" method="post" enctype="">
                                                <div class="col-md-6 col-sm-4 col-xs-8">
                                                    <input type="text" name="pesquisa" placeholder="Pesquisar" class="form-control" value="<?= $pesq != '' ? $pesq : '' ?>">
                                                </div>  
                                                <div class="col-md-2 col-sm-2 col-xs-4">
                                                    <select class="form-control" name="filtros">
                                                        <option value="-1">Todos</option>
                                                        <option value="1" <?= $filtro == '1' ? 'selected' : '' ?>>Assunto</option>
                                                        <option value="2" <?= $filtro == '2' ? 'selected' : '' ?>>Usuário</option>
                                                    </select>
                                                </div>
                                                <div class="col-md-2 col-sm-3 col-xs-6">
                                                    <button class="btn btn-primary-borded2 form-control" type="submit">
                                                        Pesquisar&nbsp;
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                </div>
                                                <div class="col-md-2 col-sm-3 col-xs-6">
                                                    <button class="btn btn-primary-borded2 form-control" type="button" onClick="showAdd()">
                                                        Novo&nbsp;
                                                        <i class="fa fa-plus"></i>
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="table-responsive" style="margin-top: 10px;">
                                            <?php
                                            $relatorio->gerarCabecalho(12);
                                            if (!empty($result)) {
                                                foreach ($result as $dados) {
                                                    
                                                    $relatorio->definirVariavel('1', "<button type='button' class='btn btn-primary4' style='width:100%' onClick=showEdit('".$dados['cod']."')><i class='pointer fa fa-edit'></i></button>");
                                                    $relatorio->definirVariavel('2', "<button type='button' class='btn btn-primary4' style='width:100%' onClick=showDelete('".$dados['cod']."')><i class='pointer fa fa-times'></i></button>");
                                                    
                                                    $relatorio->gerarRelatorio($dados);
                                                }
                                            }
                                            $relatorio->gerarRodape();
                                            ?>
                                        </div>
                                        <div id="diva-wrapper"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalAdd" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title color-primary2"><i class="fa fa-plus"></i>&nbsp;Adicionar Assunto</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="form" method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="add_assunto" class="col-form-label">Assunto:</label><label style="color:red">*</label>
                        <input type="text"  class="form-control" id="add_assunto" name="add_assunto" title="Digite o Assunto."/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary-borded2" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary3" onclick="add()">Finalizar <i class="fa fa-check"></i></button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modalEdit" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title color-primary2"><i class="fa fa-edit"></i>&nbsp;Editar Assunto</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="form" action="/atas/add" method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    <input type="hidden" id="edit_cod">
                    <div class="form-group">
                        <label for="edit_assunto" class="col-form-label">Assunto:</label><label style="color:red">*</label>
                        <input type="text"  class="form-control" id="edit_assunto" name="edit_assunto" title="Digite o Assunto."/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary-borded2" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary3" onclick="edit()">Finalizar <i class="fa fa-check"></i></button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#relatorio').DataTable({
            "language": {
                "url": "js/datatable/pt-br.json"
            },
            "ordering": false,
            "order": [],
            //"columnDefs": [ { "orderable": false, "targets": [3,4,5] }],
            "lengthChange": false,
            "searching": false
        });
    });
    
    function showAdd(){
        $('#modalAdd').modal('show');
    }
    
    function add(){
        
        var data = {
            add_assunto        : $('#add_assunto').val(),
        };
        
        if(!validaParametros(data)){
            Swal.fire({
                title: 'Atenção!',
                html: "Digite todos os campos obrigatórios (*)",
                type: 'info'
            });
            return false;
        }
        
        $.ajax({
            url: '/assunto/add',
            data: data,
            method: 'POST',
            datatype: 'json',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = jQuery.parseJSON(retorno);
                if (retorno.response) {
                    Swal.fire({
                        type: 'success',
                        title: 'Sucesso!',
                        text: retorno.msg,
                        onClose: () => {
                            loader();
                            window.location.reload();
                        }
                    });
                }
            },
            error: function () {

            },
            complete: function () {

            }
        });
    }
    
    function showDelete(cod){
        Swal.fire({
            title: 'Atenção!',
            html: 'Deseja realmente excluir?',
            type: 'info',
            showCancelButton: true,
            preConfirm: () => {
                $.ajax({
                    url: '/assunto/delete',
                    data: {cod_assunto : cod},
                    type: 'json',
                    method: 'POST',
                    beforeSend: function () {
                        loader();
                    },
                    success: function (retorno) {
                        Swal.fire({
                            title: 'Sucesso!',
                            html: 'Assunto deletado.',
                            type: 'success',
                            onClose: () => {
                                window.location.reload();
                            }
                        });
                    }
                });
            }
        });
    }
    
    function showEdit(cod){
        $.ajax({
            url: '/assunto/showEdit',
            data: {cod_assunto : cod},
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = JSON.parse(retorno);
                Swal.close();
                if(retorno.response){
                    
                    $('#edit_cod').val(retorno.result['cod']);
                    $('#edit_assunto').val(retorno.result['assunto']);
                    
                    $('#modalEdit').modal('show');
                }else{
                    Swal.fire({
                        title: 'Atenção!',
                        html: 'Assunto não encontrado.',
                        type: 'info'
                    });
                }
            }
        });
    }
    
    function edit(){
        
        var data = {
            cod_assunto         : $('#edit_cod').val(),
            assunto             : $('#edit_assunto').val(),
        };
        
        if(!validaParametros(data)){
            Swal.fire({
                title: 'Atenção!',
                html: "Digite todos os campos obrigatórios (*)",
                type: 'info'
            });
            return false;
        }
        
        $.ajax({
            url: '/assunto/edit',
            data: data,
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                Swal.fire({
                    title: 'Sucesso!',
                    html: 'Assunto editado.',
                    type: 'success',
                    onClose: () => {
                        window.location.reload();
                    }
                });
            }
        });
        
    }
    
    function showFile(arquivo){
        window.open('/arquivos/atas/'+arquivo,'_blank');
    }

</script>