<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt">            
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-book"></i>&nbsp;<label class="title">Atas de Reunião</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 10px;padding-right: 10px">
                                            <div class="col-md-6 col-sm-4 col-xs-8">
                                                <input type="text" placeholder="Pesquisar" class="form-control">
                                            </div>  
                                            <div class="col-md-2 col-sm-2 col-xs-4">
                                                <select class="form-control">
                                                    <option value="">Todos</option>
                                                    <option value="">Conteúdo</option>
                                                    <option value="">Tipo</option>
                                                    <option value="">Usuário</option>
                                                </select>
                                            </div>
                                            <div class="col-md-2 col-sm-3 col-xs-6">
                                                <button class="btn btn-primary2 form-control">
                                                    Pesquisar&nbsp;
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </div>
                                            <div class="col-md-2 col-sm-3 col-xs-6">
                                                <button class="btn btn-primary2 form-control">
                                                    Novo&nbsp;
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </div>
                                        </div>
                                        <div class="table-responsive" style="margin-top:10px">
                                            <table id="tabela" class="table table-striped table-bordered dataTable-primary" style="width:100%">
                                                <thead>
                                                    <tr>
                                                        <th>Conteúdo Sintético</th>
                                                        <th>Usuário</th>
                                                        <th>Data</th>
                                                        <th></th>
                                                        <th>Alterar</th>
                                                        <th>Excluir</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr style="text-align: left">
                                                        <td>Práticas de Organização</td>
                                                        <td>Claudio Cardoso</td>
                                                        <td>27/05/2019</td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Visualizar</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Metas para o 2° Semestre</td>
                                                        <td>Jorge da Silva</td>
                                                        <td>20/05/2019</td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Visualizar</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Processos Seletivos</td>
                                                        <td>Jorge da Silva</td>
                                                        <td>13/05/2019</td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Visualizar</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Reunião Mensal</td>
                                                        <td>Jorge da Silva</td>
                                                        <td>02/05/2019</td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Visualizar</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Planejamento de Atividades</td>
                                                        <td>Tayná Campos</td>
                                                        <td>23/04/2019</td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Visualizar</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Planejamento IV SIADS</td>
                                                        <td>Claudio Cardoso</td>
                                                        <td>20/04/2019</td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Visualizar</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Inclusão Social de Alunos</td>
                                                        <td>Tayná Campos</td>
                                                        <td>16/04/2019</td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Visualizar</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Reunião com os Professores</td>
                                                        <td>Jorge da Silva</td>
                                                        <td>10/04/2019</td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Visualizar</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Reunião Mensal</td>
                                                        <td>Jorge da Silva</td>
                                                        <td>05/04/2019</td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Visualizar</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Definições de Orientações</td>
                                                        <td>Matheus Oliveira</td>
                                                        <td>14/03/2019</td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Visualizar</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Definições de Orientações</td>
                                                        <td>Matheus Oliveira</td>
                                                        <td>14/03/2019</td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Visualizar</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Reunião Mensal</td>
                                                        <td>Jorge da Silva</td>
                                                        <td>05/04/2019</td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Visualizar</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                </tbody>
                                            </table>   
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#tabela').DataTable({
            "language": {
                "url": "js/datatable/pt-br.json"
            },
            "order": [],
            "columnDefs": [ { "orderable": false, "targets": [3,4,5] }],
            "lengthChange": false,
            "searching": false
        });
    });

</script>