<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt">            
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-book"></i>&nbsp;<label class="title">Plano de Atividades</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 10px;padding-right: 10px">
                                            <div class="col-md-6 col-sm-4 col-xs-8">
                                                <input type="text" placeholder="Pesquisar" class="form-control">
                                            </div>  
                                            <div class="col-md-2 col-sm-2 col-xs-4">
                                                <select class="form-control">
                                                    <option value="">Todos</option>
                                                    <option value="">Conteúdo</option>
                                                    <option value="">Tipo</option>
                                                    <option value="">Usuário</option>
                                                </select>
                                            </div>
                                            <div class="col-md-2 col-sm-3 col-xs-6">
                                                <button class="btn btn-primary2 form-control">
                                                    Pesquisar&nbsp;
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </div>
                                            <div class="col-md-2 col-sm-3 col-xs-6">
                                                <button class="btn btn-primary2 form-control">
                                                    Novo&nbsp;
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </div>
                                        </div>
                                        <div style="padding: 50px 10px">
                                            <div id="calendar"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="space"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" type="text/css" href="/css/calendar/fullcalendar.min.css" />
<link rel="stylesheet" type="text/css" href="/css/calendar/agenda.css" />
<script src="/js/calendar/lib/moment.min.js"></script>
<script src="/js/calendar/fullcalendar.min.js"></script>
<script src="/js/calendar/locale/pt-br.js"></script>
<script type="text/javascript">

     $(document).ready(function () {
        $('#calendar').fullCalendar({
            defaultDate: new Date(),
            editable: true,
            eventLimit: true,
            themeSystem: 'bootstrap4',
            businessHours: false,
            defaultView: 'month',
            header: {
                center: 'title',
                left: 'addEvento', //agendaDay,agendaWeek,month
                right: 'prev,next' //today
            },
            events: [
                {
                    codigo: '1',
                    title: 'Estudos',
                    start: '2019-06-03',
                    end: '2019-06-06',
                }
                ,{
                    codigo: '2',
                    title: 'Seminários',
                    start: '2019-06-13',
                    end: '2019-06-15',
                }
                ,{
                    codigo: '3',
                    title: 'Apresentação TG',
                    start: '2019-06-24',
                    end: '2019-06-23',
                }
                ,{
                    codigo: '6',
                    title: 'Atividade em grupo',
                    start: '2019-06-07',
                    end: '2019-06-09',
                }
                ,{
                    codigo: '4',
                    title: 'Novena de Nossa Senhora',
                    start: '2019-06-17',
                    end: '2019-06-21',
                }
            ],
            eventClick: function (info) {
                console.log(info);
            }
        });
    });

</script>