<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt">            
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-book"></i>&nbsp;<label class="title">Quadro de Avisos</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 10px;padding-right: 10px">
                                            <div class="col-md-6 col-sm-4 col-xs-8">
                                                <input type="text" placeholder="Pesquisar" class="form-control">
                                            </div>  
                                            <div class="col-md-2 col-sm-2 col-xs-4">
                                                <select class="form-control">
                                                    <option value="">Todos</option>
                                                    <option value="">Assunto</option>
                                                    <option value="">Nível de Escolaridade</option>
                                                </select>
                                            </div>
                                            <div class="col-md-2 col-sm-3 col-xs-6">
                                                <button class="btn btn-primary2 form-control">
                                                    Pesquisar&nbsp;
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </div>
                                            <div class="col-md-2 col-sm-3 col-xs-6">
                                                <button class="btn btn-primary2 form-control" onClick="add()">
                                                    Novo&nbsp;
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </div>
                                        </div>
                                        <div class="table-responsive" style="margin-top:10px">
                                            <table id="tabela" class="table table-striped table-bordered dataTable-primary" style="width:100%">
                                                <thead>
                                                    <tr>
                                                        <th>Assunto</th>
                                                        <th>Descrição</th>
                                                        <th>Nível Escolaridade</th>
                                                        <th>Data Inicio</th>
                                                        <th>Data Fim</th>
                                                        <th>Alterar</th>
                                                        <th>Excluir</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr style="text-align: left">
                                                        <td>Processo Seletivo</td>
                                                        <td>O processo seletivo de 2019 foi aberto. Inscreva-se.</td>
                                                        <td align="center">Mestrado</td>
                                                        <td>20/05/2019</td>
                                                        <td>20/06/2019</td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Atualização de suas informações</td>
                                                        <td>Por favor, mantenha sempre suas informações atualizadas.</td>
                                                        <td align="center">Todos</td>
                                                        <td>01/04/2019</td>
                                                        <td>01/07/2019</td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Oportunidade de Estágio</td>
                                                        <td>Uma nova oportunidade de estágio surgiu em sua região.</td>
                                                        <td align="center">Tecnólogo</td>
                                                        <td>10/03/2019</td>
                                                        <td>23/04/2019</td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                </tbody>
                                            </table>   
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalAviso" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title color-primary2"><i class="fa fa-book"></i>&nbsp;Novo Aviso</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="add-assunto" class="col-form-label">Assunto:</label>
                        <input type="text" class="form-control" id="add-assunto">
                    </div>
                    <div class="form-group">
                        <label for="add-desc" class="col-form-label">Descrição:</label>
                        <input type="text" class="form-control" id="add-desc">
                    </div>
                    <div class="form-group">
                        <label for="add-escolaridade" class="col-form-label">Nível Escolaridade:</label>
                        <select class="form-control" id="add-escolaridade">
                            <option value="1">teste</option>
                        </select>
                    </div>
                    <div clas=""
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary-borded2" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary3">Finalizar <i class="fa fa-check"></i></button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#tabela').DataTable({
            "language": {
                "url": "js/datatable/pt-br.json"
            },
            "columnDefs": [ { "orderable": false, "targets": [5,6] }],
            "lengthChange": false,
            "searching": false
        });
    });
    
    function add(){
        $('#modalAviso').modal('show');
    }

</script>