<div class="col-md-12 col-xs-12">        
    <div class="main-box-body clearfix mt">                              
        <div class="login-principal">
            <div class="col-md-12 login-conteudo text-left">   
                <!--div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-lg-2 col-lg-offset-5" id="container"-->
                <div class="wrapper">
                    <div class="row" style="margin: 20px;">
                        <div class="col-md-12 text-center">
                            <img src="/img/logo/logo_preto.png" class="img-responsive img-wid" style="margin: auto; display: block;">
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <h4 class="titulo"><b>&nbsp; Recuperar Senha</b></h4>
                        </div>
                    </div>
                    <hr>
                    <form id="frmLogin" action="./menu.html" method="post" class="form">
                        <input type="hidden" name="navegador"/>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                                    <div class="input-group">
                                        <span class="input-group-addon" style="padding-right: 10px"><i class="fa fa-user"></i></span>
                                        <input type="text" id="email" name="email" class="form-control"  placeholder="Digite seu E-mail" title="Insira seu e-mail" autofocus maxlength="30" required />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-top:30px; margin-bottom:-100px">
                            <div class="col-md-6 col-xs-12 mb-min">
                                <div class="form-group">
                                    <a href="/login">
                                        <button type="button" class="btn btn-danger btn-min">
                                            <i class="fa fa-arrow-left"></i> <b>Voltar</b>
                                        </button></a>
                                </div>
                            </div>
                            <div class="col-md-6 col-xs-12 mb-min">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success btn-min" id="btnEnviar" name="btnEnviar">
                                        <b>Enviar</b> <i class="fa fa-check"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <input name="url_destino" type="hidden" value="">
                    </form>
                </div>
            </div>
        </div>    
    </div>
</div>