<div class="col-md-12 col-xs-12">        
    <div class="main-box-body clearfix mt">                              
        <div class="login-principal">
            <div class="col-md-12 login-conteudo text-left">   
                <!--div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-lg-2 col-lg-offset-5" id="container"-->
                <div class="wrapper">
                    <div class="row" style="margin: 20px;">
                        <div class="col-md-12 text-center">
                            <img src="./img/logo/logo_preto.png" class="img-wid" style="margin: auto; display: block;">
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <h4 class="titulo">
                                <b></b>&nbsp; Bem-Vindo ao <b>SISTARP!</b> 
                            </h4>
                        </div>
                    </div>
                    <hr>
                    <form id="frmLogin" action="/" method="post" class="form">
                        <input type="hidden" name="navegador"/>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                                    <div class="input-group">
                                        <span class="input-group-addon" style="padding-right: 10px"><i class="fa fa-at"></i></span>
                                        <input type="text" id="email" name="email" class="form-control"  placeholder="E-mail" title="Insira seu e-mail" autofocus maxlength="30" required />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                        <input id="senha" name="senha" class="form-control" type="password" placeholder="Senha" title="Insira sua Senha" required maxlength="15"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row" style="margin-top:30px">

                            <div class="col-md-6 col-xs-12 mb-min">
                                <div class="form-group">
                                    <a href="/cadastro">
                                        <button type="button" class="btn btn-danger btn-min">
                                            <i class="fa fa-user-plus"></i> <b>Cadastrar</b>
                                        </button></a>
                                </div>
                            </div>
                            <div class="col-md-6 col-xs-12 mb-min">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success btn-min" id="btnLogar" name="btnLogar">
                                        <b>Entrar</b> <i class="fa fa-sign-in"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="row lb-esqueceu">
                            <div class="col-md-12 text-center">
                                <div class="form-group">
                                    <a href="/esqueci-senha" class="font-pequena">Esqueceu sua Senha?</a>
                                </div>
                            </div>
                        </div>
                        <input name="url_destino" type="hidden" value="">
                    </form>
                </div>
            </div>
        </div>    
    </div>
</div> 
