<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt">            
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-book"></i>&nbsp;<label class="title">Produção de grupo</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 10px;padding-right: 10px">
                                            <div class="col-md-6 col-sm-4 col-xs-8">
                                                <input type="text" placeholder="Pesquisar" class="form-control">
                                            </div>  
                                            <div class="col-md-2 col-sm-2 col-xs-4">
                                                <select class="form-control">
                                                    <option value="">Todos</option>
                                                    <option value="">Título</option>
                                                    <option value="">Autor</option>
                                                    <option value="">Modalidade</option>
                                                    <option value="">Status</option>
                                                    <option value="">Usuário</option>
                                                </select>
                                            </div>
                                            <div class="col-md-2 col-sm-3 col-xs-6">
                                                <button class="btn btn-primary2 form-control">
                                                    Pesquisar&nbsp;
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </div>
                                            <div class="col-md-2 col-sm-3 col-xs-6">
                                                <button class="btn btn-primary2 form-control">
                                                    Novo&nbsp;
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </div>
                                        </div>
                                        <div class="table-responsive" style="margin-top:10px">
                                            <table id="tabela" class="table table-striped table-bordered dataTable-primary" style="width:100%">
                                                <thead>
                                                    <tr>
                                                        <th>Origem</th>
                                                        <th>Título</th>
                                                        <th>Autor</th>
                                                        <th>Modalidade</th>
                                                        <th>Nome</th>
                                                        <th>Qualis</th>
                                                        <th>Formato Publicação</th>
                                                        <th>Data Submissão</th>
                                                        <th>Data Publicação</th>
                                                        <th>Link</th>
                                                        <th>Status</th>
                                                        <th></th>
                                                        <th>Alterar</th>
                                                        <th>Excluir</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Ipaussu City</td>
                                                        <td>Hotel California</td>
                                                        <td>Jorge Cardoso</td>
                                                        <td>Periódico</td>
                                                        <td>Meu Nome</td>
                                                        <td>-</td>
                                                        <td>Arquivo</td>
                                                        <td>10/05/2019</td>
                                                        <td>10/05/2019</td>
                                                        <td>www.meusite.com.br</td>
                                                        <td>Em Preparação </td>
                                                        <td width="20px"><button class="btn btn-primary-borded2 form-control">Download</button></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-edit"></i></td>
                                                        <td align="center" width="10px"><i class="pointer fa fa-times"></i></td>
                                                    </tr>
                                                </tbody>
                                            </table>   
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#tabela').DataTable({
            "language": {
                "url": "js/datatable/pt-br.json"
            },
            "columnDefs": [ { "orderable": false, "targets": [4,5,6] }],
            "lengthChange": false,
            "searching": false
        });
    });

</script>