<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt">            
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary2"><i class="fa fa-book"></i>&nbsp;<label class="title">Quadro de Leitura</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 20px;padding-right: 20px">
                                            <div class="col-md-8 col-sm-8 col-xs-8">
                                                <input type="text" placeholder="Pesquisar por Material de Leitura" class="form-control">
                                            </div>   
                                            <div class="col-md-4 col-sm-4 col-xs-4">
                                                <button class="btn btn-primary2 form-control">
                                                    Pesquisar&nbsp;
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                        <div class="table-responsive">
                                            <table id="example" class="table table-striped table-bordered dataTable-primary" style="width:100%">
                                                <thead>
                                                    <tr>
                                                        <th>Título do Artigo</th>
                                                        <th>Título do periódico</th>
                                                        <th>Pesquisador</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Como zoar o Grimes</td>
                                                        <td>The arte of zoar</td>
                                                        <td>Vivangola</td>
                                                        <td><button class="btn btn-primary-borded2 form-control">DOWNLOAD</button></td>
                                                    </tr>
                                                </tbody>
                                            </table>   
                                        </div>
                                    </div>
                                </div>
                                <div class="space"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#example').DataTable({
            "language": {
                "url": "js/datatable/pt-br.json"
            },
            "columnDefs": [ { "orderable": false, "targets": [3] }],
            "lengthChange": false,
            "searching": false
        });
    });

</script>