<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt">            
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-book"></i>&nbsp;<label class="title">Quadro de Disponibilidade</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 10px;padding-right: 10px">
                                            <div class="col-md-12">
                                                <div class="col-md-2 col-sm-3 col-xs-4">
                                                    <div class="form-inline">
                                                        <label for="mes">Mês:</label>
                                                        <div class="col-md-2 col-sm-2 col-xs-8" id="mes" name="mes">
                                                            <select class="form-control">
                                                                <option value="">Janeiro</option>
                                                                <option value="">Fevereiro</option>
                                                                <option value="">Março</option>
                                                                <option value="">Abril</option>
                                                                <option value="" selected>Maio</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-3 col-sm-3 col-xs-4">
                                                    <div class="form-inline">
                                                        <label for="ano">Ano:</label>
                                                        <div class="col-md-2 col-sm-2 col-xs-8" id="ano" name="ano">
                                                            <select class="form-control">
                                                                <option value="">2017</option>
                                                                <option value="">2018</option>
                                                                <option value="" selected>2019</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-2 col-md-offset-5 col-sm-2 col-sm-offset-4 col-xs-4">
                                                    <button class="btn btn-primary2 form-control">
                                                        Novo&nbsp;
                                                        <i class="fa fa-plus"></i>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                        <div style="padding: 10px">
                                            <div id="calendar"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet" type="text/css" href="/css/calendar/fullcalendar.min.css" />
<link rel="stylesheet" type="text/css" href="/css/calendar/agenda.css" />
<script src="/js/calendar/lib/moment.min.js"></script>
<script src="/js/calendar/fullcalendar.js"></script>
<script src="/js/calendar/locale/pt-br.js"></script>


<script type="text/javascript">
    $(document).ready(function () {
        $('#calendar').fullCalendar({
            defaultDate: new Date(),
            editable: true,
            firstHour: 6,
            eventLimit: true,
            themeSystem: 'bootstrap4',
            businessHours: false,
            defaultView: 'agendaWeek',
            header: {
                center: 'title',
                left: 'addEvento', //agendaDay,agendaWeek,month
                right: 'prev,next' //today
            },
            events: [
                {
                    codigo: '1',
                    title: 'Claudio Cardoso',
                    start: '2019-05-20 12:00:00',
                    end: '2019-05-20 15:00:01',
                },
                {
                    codigo: '2',
                    title: 'Claudio Cardoso',
                    start: '2019-05-21 08:00:00',
                    end: '2019-05-21 12:00:01',
                },
                {
                    codigo: '3',
                    title: 'Claudio Cardoso',
                    start: '2019-05-22 08:00:00',
                    end: '2019-05-22 12:00:01',
                },
                {
                    codigo: '4',
                    title: 'Claudio Cardoso',
                    start: '2019-05-23 13:00:00',
                    end: '2019-05-23 17:00:01',
                },
                {
                    codigo: '5',
                    title: 'Claudio Cardoso',
                    start: '2019-05-24 13:00:00',
                    end: '2019-05-24 17:00:01',
                },
                {
                    codigo: '6',
                    title: 'Tayná Campos',
                    start: '2019-05-20 19:00:00',
                    end: '2019-05-20 23:00:01',
                },
                {
                    codigo: '6',
                    title: 'Tayná Campos',
                    start: '2019-05-21 19:00:00',
                    end: '2019-05-21 23:00:01',
                },
                {
                    codigo: '6',
                    title: 'Tayná Campos',
                    start: '2019-05-22 19:00:00',
                    end: '2019-05-22 23:00:01',
                },
                {
                    codigo: '6',
                    title: 'Tayná Campos',
                    start: '2019-05-23 19:00:00',
                    end: '2019-05-23 23:00:01',
                },
                {
                    codigo: '6',
                    title: 'Tayná Campos',
                    start: '2019-05-24 19:00:00',
                    end: '2019-05-24 23:00:01',
                },
            ],
            eventClick: function (info) {
                console.log(info);
            }
        });
    });
</script>