<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt">            
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-book"></i>&nbsp;<label class="title">Plano de Atividades</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 10px;padding-right: 10px">
                                            <form action="/quadro-leitura" method="post" enctype=""> 
                                                <?php if($is_adm == 1):?>
                                                <br>
                                                <div class="form-inline">
                                                    <div class="col-md-offset-3 col-md-1 col-sm-3 col-xs-6 text-right">
                                                        <label class="col-form-label">Périodo: </label>
                                                    </div>
                                                    <div class="col-md-2 col-sm-3 col-xs-6">
                                                        <input type="date" id="dt_ini" class="form-control">
                                                    </div>
                                                    <div class="col-md-1 col-sm-3 col-xs-6">
                                                        até
                                                    </div>
                                                    <div class="col-md-2 col-sm-3 col-xs-6">
                                                        <input type="date" id="dt_ini" class="form-control">
                                                    </div>
                                                </div>
                                                <br>
                                                <?php endif; ?>
                                                <div class="col-md-6 col-sm-4 col-xs-8">
                                                    <input type="text" name="pesquisa" placeholder="Pesquisar" class="form-control" value="<?= $pesq != '' ? $pesq : '' ?>">
                                                </div>  
                                                <div class="col-md-2 col-sm-2 col-xs-4">
                                                    <select class="form-control" name="filtros">
                                                        <option value="-1">Todos</option>
                                                        <option value="1" <?= $filtro == '1' ? 'selected' : '' ?>>Tipo de Atividade</option>
                                                        <option value="2" <?= $filtro == '2' ? 'selected' : '' ?>>Status</option>
                                                        <option value="3" <?= $filtro == '3' ? 'selected' : '' ?>>Mês</option>
                                                        <option value="4" <?= $filtro == '4' ? 'selected' : '' ?>>Ano</option>
                                                        <?php if($is_adm == 1):?>
                                                            <option value="5" <?= $filtro == '5' ? 'selected' : '' ?>>Usuário</option>
                                                        <?php endif; ?>
                                                    </select>
                                                </div>
                                                <div class="col-md-2 col-sm-3 col-xs-6">
                                                    <button class="btn btn-primary-borded2 form-control" type="submit">
                                                        Pesquisar&nbsp;
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                </div>
                                                <div class="col-md-2 col-sm-3 col-xs-6">
                                                    <button class="btn btn-primary-borded2 form-control" type="button" onClick="showAdd()">
                                                        Novo&nbsp;
                                                        <i class="fa fa-plus"></i>
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                        
                                        <div class="table-responsive" style="margin-top: 10px;">
                                            <?php
                                            $relatorio->gerarCabecalho(12);
                                            if (!empty($result)) {
                                                foreach ($result as $dados) {
                                                    $relatorio->definirVariavel('2', "<button type='button' class='btn btn-primary4' style='width:100%' onClick=showEdit('".$dados['cod']."')><i class='pointer fa fa-edit'></i></button>");
                                                    $relatorio->definirVariavel('3', "<button type='button' class='btn btn-primary4' style='width:100%' onClick=showDelete('".$dados['cod']."')><i class='pointer fa fa-times'></i></button>");
                                                    
                                                    $relatorio->gerarRelatorio($dados);
                                                }
                                            }
                                            $relatorio->gerarRodape();
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalAdd" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title color-primary2"><i class="fa fa-plus"></i>&nbsp;Adicionar Atividade</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="formAdd" method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="add_desc" class="col-form-label">Descrição:</label>
                        <input type="text"  class="form-control" id="add_desc" name="add_desc" maxlength="200" title="Digite a Descrição da Atividade."/>
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-6">
                            <label for="add_tipo" class="col-form-label">Tipo de Atividade:</label>
                            <select id="add_tipo" class="form-control input-group-lg" name="add_tipo" title="Selecione o tipo da atividade.">
                                <?php foreach($tipos as $dados): ?>
                                        <option value="<?= $dados['cod'] ?>"> <?= $dados['descricao'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>

                        <div class="form-group col-xs-6">
                            <label for="add_status" class="col-form-label">Status da Atividade:</label>
                            <select id="add_status" class="form-control input-group-lg" name="add_status" title="Status da atividade.">
                                <?php foreach($status as $dados): ?>
                                        <option value="<?= $dados['cod'] ?>"> <?= $dados['descricao'] ?></option>
                                <?php endforeach; ?>
                             </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-2">
                            <label for="add_mes" class="col-form-label">Mês:</label>
                            <input id="add_mes" class="form-control input-group-lg" type="text" name="add_mes" data-mask="00" placeholder="Mês"/>
                        </div>
                        
                        <div class="form-group col-xs-2">
                            <label for="add_ano" class="col-form-label">Ano:</label>
                            <input id="add_ano" class="form-control input-group-lg" type="text" name="add_ano" data-mask="0000" placeholder="Ano"/>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary-borded2" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary3" onclick="add()">Finalizar <i class="fa fa-check"></i></button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modalEdit" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title color-primary2"><i class="fa fa-plus"></i>&nbsp;Adicionar Material</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="form" method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    <input type="hidden" id="edit_cod"/>
                    <div class="form-group">
                        <label for="edit_artigo" class="col-form-label">Título Artigo:</label>
                        <input type="text"  class="form-control" id="edit_artigo" name="edit_artigo" maxlength="200" title="Digite o Título do Artigo."/>
                    </div>
                    <div class="form-group">
                        <label for="edit_periodico" class="col-form-label">Título Periódico:</label>
                        <input type="text"  class="form-control" id="edit_periodico" maxlength="200" name="edit_periodico" title="Digite o Título Periódico."/>
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-6">
                            <label for="edit_base" class="col-form-label">Base:</label>
                            <input id="edit_base" class="form-control input-group-lg" maxlength="100" type="text" name="edit_base"/>
                        </div>

                        <div class="form-group col-xs-6">
                            <label for="edit_datapesq" class="col-form-label">Data da Pesquisa:</label>
                            <input id="edit_datapesq" class="form-control input-group-lg" type="date" name="edit_datapesq"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-2">
                            <label for="edit_pginicial" class="col-form-label">Pag Inícial:</label>
                            <input id="edit_pginicial" class="form-control input-group-lg" type="text" name="edit_pginicial" data-mask="00000"/>
                        </div>

                        <div class="form-group col-xs-2">
                            <label for="edit_pgfim" class="col-form-label">Pag Final:</label>
                            <input id="edit_pgfim" class="form-control input-group-lg" type="text" name="edit_pgfim" data-mask="00000"/>
                        </div>
                        
                        <div class="form-group col-xs-2">
                            <label for="edit_volume" class="col-form-label">Volume:</label>
                            <input id="edit_volume" class="form-control input-group-lg" type="text" name="edit_volume" data-mask="00000"/>
                        </div>

                        <div class="form-group col-xs-2">
                            <label for="edit_numero" class="col-form-label">Numero:</label>
                            <input id="edit_numero" class="form-control input-group-lg" type="text" name="edit_numero" data-mask="00000"/>
                        </div>
                        
                        <div class="form-group col-xs-2">
                            <label for="edit_mes" class="col-form-label">Mês:</label>
                            <input id="edit_mes" class="form-control input-group-lg" type="text" name="edit_mes" data-mask="00" placeholder="Mês"/>
                        </div>
                        
                        <div class="form-group col-xs-2">
                            <label for="edit_ano" class="col-form-label">Ano:</label>
                            <input id="edit_ano" class="form-control input-group-lg" type="text" name="edit_ano" data-mask="0000" placeholder="Ano"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit_autor "class="col-form-label">Autor(es):</label>
                        <input type="text"  class="form-control" id="edit_autor" maxlength="200" name="edit_autor" title="Digite o(s) Autor(s)."/>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary-borded2" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary3" onclick="edit()">Finalizar <i class="fa fa-check"></i></button>
                </div>
            </form>
        </div>
    </div>
</div>


<script type="text/javascript">

    $(document).ready(function () {
        $('#relatorio').DataTable({
            "language": {
                "url": "js/datatable/pt-br.json"
            },
            "pageLength": 10, 
            "ordering": false,
            "lengthChange": false,
            "searching": false,
            "ordering": false,
        });
    });
    
    function showAdd(){
        $('#modalAdd').modal('show');
    }
    
    function add(){
        
        var data = {
            descricao    : $('#add_desc').val(),
            tipo         : $('#add_tipo').val(),
            status       : $('#add_status').val(),
            ano          : $('#add_ano').val(),
            mes          : $('#add_mes').val()
        };
        
        if(!validaParametros(data)){
            Swal.fire({
                title: 'Atenção!',
                html: "Digite todos os campos.",
                type: 'info'
            });
            return false;
        }
        
        var options = {
            url: '/plano-atividades/add',
            type: 'POST',
            dataType: 'json',
            cache: false,
            success: function (retorno) {
                if (retorno.response) {
                    Swal.fire({
                        title: 'Sucesso!',
                        html: retorno.msg,
                        type: 'success',
                        onClose: () => {
                            window.location.reload();
                        }
                    });
                        
                }else{
                    Swal.fire({
                        title: 'Atenção!',
                        html: retorno.msg,
                        type: 'warning'
                    });
                }
            }
        };

        $('#formAdd').ajaxSubmit(options);
        return false;
    }
    
    function showEdit(cod){
        $.ajax({
            url: '/quadro-leitura/showEdit',
            data: {cod : cod},
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = JSON.parse(retorno);
                Swal.close();
                if(retorno.response){
                    $('#edit_cod').val(retorno.result['cod']);
                    $('#edit_base').val(retorno.result['base']),
                    $('#edit_datapesq').val(retorno.result['dt_pesq']),
                    $('#edit_periodico').val(retorno.result['titulo_periodico']),
                    $('#edit_ano').val(retorno.result['ano']),
                    $('#edit_mes').val(retorno.result['mes']),
                    $('#edit_volume').val(retorno.result['volume']),
                    $('#edit_numero').val(retorno.result['numero']),
                    $('#edit_artigo').val(retorno.result['titulo_artigo']),
                    $('#edit_autor').val(retorno.result['autor']),
                    $('#edit_pginicial').val(retorno.result['pagina_inicial']),
                    $('#edit_pgfim').val(retorno.result['pagina_final']),
                    
                    $('#modalEdit').modal('show');
                }else{
                    Swal.fire({
                        title: 'Atenção!',
                        html: 'Material não encontrado.',
                        type: 'info'
                    });
                }
            }
        });
    }
    
    function edit(){
        
        var data = {
            cod                 : $('#edit_cod').val(),
            base                : $('#edit_base').val(),
            data_pesq           : $('#edit_datapesq').val(),
            titulo_periodico    : $('#edit_periodico').val(),
            ano                 : $('#edit_ano').val(),
            mes                 : $('#edit_mes').val(),
            volume              : $('#edit_volume').val(),
            numero              : $('#edit_numero').val(),
            titulo_artigo       : $('#edit_artigo').val(),
            autor               : $('#edit_autor').val(),
            pginicial           : $('#edit_pginicial').val(),
            pgfim               : $('#edit_pgfim').val(),
            interesse           : '5'
        };
        
        console.log(data);
        
        if(!validaParametros(data)){
            Swal.fire({
                title: 'Atenção!',
                html: "Digite todos os campos.",
                type: 'info'
            });
            return false;
        }
        
        if(!validarData(data.data_pesq)){
            Swal.fire({
                title: 'Atenção!',
                html: "A data de pesquisa não é válida.",
                type: 'info'
            });
            return false;
        }
        
        $.ajax({
            url: '/quadro-leitura/edit',
            data: data,
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = JSON.parse(retorno);
                Swal.fire({
                    title: 'Sucesso!',
                    html: retorno.msg,
                    type: 'success',
                    onClose: () => {
                        window.location.reload();
                    }
                });
            }
        });
    }
    
    function showDelete(cod){
        Swal.fire({
            title: 'Atenção!',
            html: 'Deseja realmente excluir?',
            type: 'info',
            showCancelButton: true,
            preConfirm: () => {
                $.ajax({
                    url: '/plano-atividades/delete',
                    data: {cod : cod},
                    type: 'json',
                    method: 'POST',
                    beforeSend: function () {
                        loader();
                    },
                    success: function (retorno) {
                        retorno = JSON.parse(retorno);
                        Swal.fire({
                            title: 'Sucesso!',
                            html: retorno.msg,
                            type: 'success',
                            onClose: () => {
                                window.location.reload();
                            }
                        });
                    }
                });
            }
        });
    }
    
    function showFile(arquivo){
        window.open('/arquivos/leitura/'+arquivo,'_blank');
    }

</script>