<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt">            
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-book"></i>&nbsp;<label class="title">Meus Trabalhos</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 10px;padding-right: 10px">
                                            <form action="/trabalho-correcao" method="post" enctype="">
                                                <div class="col-md-6 col-sm-4 col-xs-8">
                                                    <input type="text" name="pesquisa" placeholder="Pesquisar" class="form-control" value="<?= $pesq != '' ? $pesq : '' ?>">
                                                </div>  
                                                <div class="col-md-2 col-sm-2 col-xs-4">
                                                    <select class="form-control" name="filtros">
                                                        <option value="-1">Todos</option>
                                                        <option value="1" <?= $filtro == '1' ? 'selected' : '' ?>>Membro</option>
                                                        <option value="2" <?= $filtro == '2' ? 'selected' : '' ?>>Modalidade</option>
                                                        <option value="3" <?= $filtro == '3' ? 'selected' : '' ?>>Status</option>
                                                        
                                                    </select>
                                                </div>
                                                <div class="col-md-2 col-sm-3 col-xs-6">
                                                    <button class="btn btn-primary-borded2 form-control" type="submit">
                                                        Pesquisar&nbsp;
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                </div>
                                                <div class="col-md-2 col-sm-3 col-xs-6">
                                                    <button class="btn btn-primary-borded2 form-control" type="button" onClick="showAdd()">
                                                        Novo&nbsp;
                                                        <i class="fa fa-plus"></i>
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                        
                                        <div class="table-responsive" style="margin-top: 10px;">
                                            <?php
                                            $relatorio->gerarCabecalho(12);
                                            if (!empty($result)) {
                                                foreach ($result as $dados) {
                                                    $relatorio->definirVariavel('1', "<button type='button' class='btn btn-primary4' style='width:100%' onClick= window.open('/trabalho-correcao/historico?c=".$dados['cod_correcao']."&r=0','_self');('".$dados['cod_correcao']."')><i class='pointer fa fa-external-link'></i></button>");
                                                    /*if(!$dados['status']){
                                                        $relatorio->definirVariavel('2', "<button type='button' class='btn btn-primary4' style='width:100%' onClick=showEdit('".$dados['cod_correcao']."')><i class='pointer fa fa-edit'></i></button>");
                                                    }else{
                                                        $relatorio->definirVariavel('2', "");
                                                    }*/
                                                    if($dados['qtd'] <= 1){
                                                        $relatorio->definirVariavel('3', "<button type='button' class='btn btn-primary4' style='width:100%' onClick=showDelete('".$dados['cod_correcao']."')><i class='pointer fa fa-times'></i></button>");
                                                    }else{
                                                        $relatorio->definirVariavel('3', "");
                                                    }
                                                    $relatorio->gerarRelatorio($dados);
                                                }
                                            }
                                            $relatorio->gerarRodape();
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalAdd" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title color-primary2"><i class="fa fa-plus"></i>&nbsp;Adicionar Trabalho para Correção</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="formAdd" method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-xs-6">
                            <label for="add_escolaridade" class="col-form-label">Nivel escolaridade:</label><label style="color:red">*</label>
                            <select class="form-control" name="add_escolaridade" id="add_escolaridade">
                                <option value="0">Todos</option>
                                <?php foreach($escolaridade as $dados):?>
                                        <option value="<?= $dados['cod_nivel']?>"><?= $dados['descricao'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group col-xs-6">
                            <label for="add_membro" class="col-form-label">Membro:</label>
                            <select class="form-control" name="add_membro" id="add_membro">
                                <option value="0">Todos</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <label for="add_modalidade" class="col-form-label">Modalidade:</label>
                            <input id="add_modalidade" class="form-control input-group-lg" maxlength="100" type="text" name="add_modalidade"/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <label for="add_observacao" class="col-form-label">Observação:</label><label style="color:red">*</label>
                            <input type="text" class="form-control obg" id="add_observacao" maxlength="200" name="add_observacao" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <label for="add_arquivo" class="obg col-form-label">Arquivo (pdf,doc,docx):</label><label style="color:red">*</label>
                            <input type="file" accept=".doc,.docx,.pdf" class="form-control" name="add_arquivo" id="add_arquivo">
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary-borded2" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary3" onclick="add()">Finalizar <i class="fa fa-check"></i></button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modalEdit" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title color-primary2"><i class="fa fa-plus"></i>&nbsp;Editar Produção de Grupo</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="formEdit" method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="row">
                        <input type="hidden" name="edit_cod" id="edit_cod"/>
                        <div class="form-group col-xs-6">
                            <label for="edit_membro" class="col-form-label">Membro:</label><label style="color:red">*</label>
                            <select class="form-control" name="edit_membro" id="edit_membro">
                                <option value="-1">Selecione</option>
                                <?php foreach($membros as $dados):?>
                                        <option value="<?= $dados['cod_usuario']?>"><?= $dados['nome'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group col-xs-6">
                            <label for="edit_modalidade" class="col-form-label">Modalidade:</label>
                            <input id="edit_modalidade" class="form-control input-group-lg" maxlength="100" type="text" name="edit_modalidade"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="edit_observacao" class="col-form-label">Observação:</label><label style="color:red">*</label>
                        <input type="text" class="form-control obg" id="edit_observacao" maxlength="200" name="edit_observacao" />
                    </div>
                    <div class="form-group">
                        <label for="edit_arquivo" class="obg col-form-label">Arquivo (pdf,doc,docx):</label><label style="color:red">*</label>
                        <input type="file" accept=".doc,.docx,.pdf" class="form-control" name="edit_arquivo" id="edit_arquivo">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary-borded2" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary3" onclick="edit()">Finalizar <i class="fa fa-check"></i></button>
                </div>
            </form>
        </div>
    </div>
</div>


<script type="text/javascript">

    $(document).ready(function () {
        $('#relatorio').DataTable({
            "language": {
                "url": "js/datatable/pt-br.json"
            },
            "pageLength": 10, 
            "ordering": false,
            "lengthChange": false,
            "searching": false,
            "ordering": false,
        });
    });
    
    function showAdd(){
        $('#modalAdd').modal('show');
    }
    
    function add(){
        
        var data = {};
        $.each($("#formAdd .obg").serializeArray(), function (_, field) {
            data[field.name] = field.value;
        });
        
        if(!validaParametros(data)){
            Swal.fire({
                title: 'Atenção!',
                html: "Digite todos os campos obrigatórios (*)",
                type: 'info'
            });
            return false;
        }
      
        var options = {
            url: '/trabalho-correcao/add',
            type: 'POST',
            dataType: 'json',
            cache: false,
            success: function (retorno) {
                if (retorno.response) {
                    Swal.fire({
                        title: 'Sucesso!',
                        html: retorno.msg,
                        type: 'success',
                        onClose: () => {
                            window.location.reload();
                        }
                    });
                        
                }else{
                    Swal.fire({
                        title: 'Atenção!',
                        html: retorno.msg,
                        type: 'warning'
                    });
                }
            }
        };
        loader()
        $('#formAdd').ajaxSubmit(options);
        return false;
    }
    
    function showEdit(cod){
        $.ajax({
            url: '/trabalho-correcao/showEdit',
            data: {cod : cod},
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = JSON.parse(retorno);
                Swal.close();
                if(retorno.response){
                    $('#edit_cod').val(retorno.result['cod_correcao']);
                    $('#edit_membro').val(retorno.result['destinatario_fk']);
                    $('#edit_modalidade').val(retorno.result['modalidade']),
                    $('#edit_observacao').val(retorno.result['observacao']),
                    $('#modalEdit').modal('show');
                }else{
                    Swal.fire({
                        title: 'Atenção!',
                        html: 'Produção não encontrada.',
                        type: 'info'
                    });
                }
            }
        });
    }
    
    $("#add_escolaridade").change(function(){
        $.ajax({
            url: '/trabalho-correcao/getMembros',
            data: {nivel : $(this).val() },
            type: 'json',
            method: 'POST',
            beforeSend: function () {
                loader();
            },
            success: function (retorno) {
                retorno = JSON.parse(retorno);
                Swal.close();
                if(retorno.response){
                    html="<option value='0'>Todos</option>";
                    $.each(retorno.membros, function(index, data){
                        html= html + "<option value='"+data.cod_usuario+"' >"+data.nome+"</option>";
                    });
                    $("#add_membro").html(html);
                }else{
                    Swal.fire({
                        title: 'Atenção!',
                        html: 'Nenhum membro encontrado!',
                        type: 'info'
                    });
                }
            }
        });
        
    });
      
    function edit(){
        
        var data = {};
        $.each($("#formEdit .obg").serializeArray(), function (_, field) {
            data[field.name] = field.value;
        });
        
        if(!validaParametros(data)){
            Swal.fire({
                title: 'Atenção!',
                html: "Digite todos os campos obrigatórios (*)",
                type: 'info'
            });
            return false;
        }

        var options = {
            url: '/trabalho-correcao/edit',
            type: 'POST',
            dataType: 'json',
            cache: false,
            success: function (retorno) {
                if (retorno.response) {
                    Swal.fire({
                        title: 'Sucesso!',
                        html: retorno.msg,
                        type: 'success',
                        onClose: () => {
                            window.location.reload();
                        }
                    });
                        
                }else{
                    Swal.fire({
                        title: 'Atenção!',
                        html: retorno.msg,
                        type: 'warning'
                    });
                }
            }
        };

        $('#formEdit').ajaxSubmit(options);
        return false;
    }
    
    function showDelete(cod){
        Swal.fire({
            title: 'Atenção!',
            html: 'Deseja realmente excluir?',
            type: 'info',
            showCancelButton: true,
            preConfirm: () => {
                $.ajax({
                    url: '/trabalho-correcao/delete',
                    data: {cod : cod},
                    type: 'json',
                    method: 'POST',
                    beforeSend: function () {
                        loader();
                    },
                    success: function (retorno) {
                        retorno = JSON.parse(retorno);
                        Swal.fire({
                            title: 'Sucesso!',
                            html: retorno.msg,
                            type: 'success',
                            onClose: () => {
                                window.location.reload();
                            }
                        });
                    }
                });
            }
        });
    }
    
    function showFile(arquivo){
        window.open('/arquivos/trabalho-correcao/'+arquivo,'_blank');
    }

</script>