<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix mt">            
                <div class="container pd-0">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-6 pd-0">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary2"><i class="fa fa-user"></i>&nbsp;<label class="title">Manter Termo Inicial</label></div>
                                    <div class="info" style="height: 800px;padding:30px;">
                                        <hr>
                                        <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12 pd-0">                    
                                            <form id="frmPreCadastro" action="" method="post" class="form">
                                                <div class="row" style="margin-bottom: 20px">
                                                    <div class="col-md-12 text-left">
                                                        <label class="control-label" for="termo">Termo:</label><label style="color:red">*</label>
                                                        <textarea name="termo" id="termo" maxlength="8000" class="form-control" style="height: 600px;resize: none;"><?= $termo ?></textarea>
                                                    </div>
                                                </div>
                                                <br>
                                                <div class="row">
                                                    <div class="col-md-12 text-left">
                                                        <button type="button" class="btn btn-primary3 btn-block info" onclick="salvar()"><?= $termo == "" ? "Incluir " : "Alterar " ?><i class="fa fa-pencil"></i></button>
                                                    </div>
                                                </div>    
                                            </form>
                                        </div>                                                              
                                    </div>
                                </div>
                            </div> 
                        </div>
                    </div>      
                </div>
            </div>
        </div>
    </div>
</div>
<div class="page-content">
    <div id="footer">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="col-xs-12">
                    <div align="center" style="margin:10px;"><img src="/img/logo/unesp.png" alt="" class="unesp"></div>
                </div>    
            </div> 
        </div>
    </div>    
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.2.0/zxcvbn.js" type="text/javascript"></script>
<script type="text/javascript">
    
    function salvar(){
            
            var data = {
                termo       : $('#termo').val(),
                cod         : '<?= $cod_termo ?>'
            };
            
            if(data.termo.length >= 8000){
                Swal.fire({
                    title: 'Atenção!',
                    html: "Permitido apenas 8000 caracteres.",
                    type: 'info'
                });
                return false;
            }
            
            if(!validaParametros(data)){
                Swal.fire({
                    title: 'Atenção!',
                    html: "Digite todos os campos obrigatórios (*)",
                    type: 'info'
                });
                return false;
            }
            
            $.ajax({
                url: '/sistema/salvarTermo',
                data: data,
                method: 'POST',
                datatype: 'json',
                beforeSend: function () {
                    loader();
                },
                success: function (retorno) {
                    retorno = jQuery.parseJSON(retorno);
                    Swal.fire({
                        type: 'success',
                        title: 'Sucesso!',
                        text: 'Salvo com sucesso.',
                        onClose: () => { window.location='/sistema/termos' }
                    });
                },
                error: function () {

                },
                complete: function () {

                }
            });
    }
    
</script>