<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco">
            <div class="main-box-body clearfix mt" style="margin-top: 2px !important;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-list"></i>&nbsp;<label class="title">Relatório de Aceite</label></div>
                                    <div class="info" style="min-height:450px">
                                        <div class="row" style="padding-left: 10px;padding-right: 10px;margin-top: 10px;margin-bottom: 20px;">
                                            <form action="/sistema/relatorio-termo" method="post" enctype="">
                                                <div class="col-md-8 col-sm-6 col-xs-8">
                                                </div>  
                                                <div class="col-md-2 col-sm-2 col-xs-4">
                                                    <select class="form-control" name="filtros">
                                                        <option value="-1" <?= $filtro == '-1' ? 'selected' : '' ?>>Todos</option>
                                                        <option value="1" <?= $filtro == '1' ? 'selected' : '' ?>>Termo aceito</option>
                                                        <option value="2" <?= $filtro == '2' ? 'selected' : '' ?>>Termo não aceito</option>
                                                    </select>
                                                </div>
                                                <div class="col-md-2 col-sm-3 col-xs-6">
                                                    <button class="btn btn-primary-borded2 form-control" type="submit">
                                                        Pesquisar&nbsp;
                                                        <i class="fa fa-search"></i>
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                        <div class="table-responsive" style="margin-top: 10px;">
                                            <?php
                                            $relatorio->gerarCabecalho(12);
                                            if ($result) {
                                                foreach ($result as $dados) {
                                                    $relatorio->definirVariavel('1', $dados['aceite'] == 1 ? "<label style='color:green'> Aceito </label>" : "<label style='color:red'> Não aceito </label>");
                                                    $relatorio->gerarRelatorio($dados);
                                                }
                                            }
                                            $relatorio->gerarRodape();
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#relatorio').DataTable({
            "language": {
                "url": "/js/datatable/pt-br.json"
            },
            //"columnDefs": [ { "orderable": false, "targets": [5,6] }],
            "lengthChange": false,
            "searching": false,
            "ordering": false
        });
    });

</script>