<?php
use Zend\Session\Container;
$sessao = new Container('usuario');
?>

<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix">  
                <div class="row panels">
                    <div class="col-md-12 pd-0" style="clear: both;">
                        <div class="box">                           
                            <div class="icon">
                                <div class="info" style="display:flex;margin-top: 1px">
                                    <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12 pd-0" style="margin-bottom: 10px;width:100%;">         
                                        <div class="col-md-12 mt-3">
                                            <div class="jumbotron" style='background: #f5f5f5'>
                                                <h1 class="display-4">Termo Inicial</h1>
                                                <hr class="my-4">
                                                <p class="lead" style="text-align: justify"><?= $termo ?></p>
                                                <br><br>
                                                <p class="lead">
                                                    <button class="btn btn-primary4 btn-lg" onclick="termo(1)">Aceito &nbsp;<i class='fa fa-thumbs-up'></i></button>
                                                    <button class="btn btn-primary8 btn-lg" style="background-color:#d2d2d2" onclick="termo(2)">Não aceito &nbsp;<i class='fa fa-thumbs-down'></i></button>
                                                </p>
                                            </div>
                                        </div>
                                    </div>                                                            	
                                </div>
                            </div>
                        </div> 
                    </div>
                </div>
                <div class="page-content"  style="margin-top: 20px">
                    <div id="footer">
                        <div class="row">
                            <div class="col-xs-12 col-md-12">
                                <div align="center" style="margin:10px;"><img src="/img/logo/unesp.png" alt="" class="unesp">&copy; 2019 - <?= date('Y') ?></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function termo(aceite){
        Swal.fire({
            title: 'Atenção!',
            html: 'Deseja realmente <b>'+ (aceite === 1 ? 'aceitar' : 'não aceitar') +'</b> o termo inicial?',
            type: 'info',
            showCancelButton: true,
            preConfirm: () => {
                $.ajax({
                    url: '/perfil/termo',
                    data: {
                        aceite     : aceite,
                        termo      : <?= $cod ?>
                    },
                    type: 'json',
                    method: 'POST',
                    beforeSend: function () {
                        loader();
                    },
                    success: function (retorno) {
                        retorno = JSON.parse(retorno);
                        location.href = '/';
                    }
                });
            }
        });
    }
</script>