<?php
use Zend\Session\Container;
$sessao = new Container('usuario');
?>

<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix">  
                <div class="row panels">
                    <div class="col-md-12 pd-0" style="clear: both;">
                        <div class="box">                           
                            <div class="icon">
                                <div class="info" style="height: 550px;margin-top: 1px">
                                    <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12 pd-0" style="margin-bottom: 10px;width:100%;">         
                                        <div class="col-md-12 mt-3">
                                            <div class="jumbotron" style='background: #f5f5f5'>
                                                <h1 class="display-4">Olá, <?= $nome_usuario ?>!</h1>
                                                <hr class="my-4">
                                                <p class="lead">Bem vindo ao Grupo de Estudos EDACI.</p>
                                                <p class="lead">Antes de continuar no sistema, precisamos que você responda um questionário criado pelo <b>administrador do grupo</b> e em seguida informe alguns dados pessoais ao sistema.</p>
                                                <p class="lead">Este processo pode levar em torno de 5-10 minutos para ser completado.</p>
                                                <br>
                                                <br>
                                                <br>
                                                <p class="lead">
                                                    <a class="btn btn-primary4 btn-lg" href="#" role="button">Responder Questionário &nbsp;<i class='fa fa-edit'></i></a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>                                                            	
                                </div>
                            </div>
                        </div> 
                    </div>
                </div>
                <div class="page-content"  style="margin-top: 20px">
                    <div id="footer">
                        <div class="row">
                            <div class="col-xs-12 col-md-12">
                                <div align="center" style="margin:10px;"><img src="/img/logo/unesp.png" alt="" class="unesp">&copy; 2019 - <?= date('Y') ?></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#relatorio').DataTable({
            "language": {
                "url": "js/datatable/pt-br.json"
            },
            //"columnDefs": [ { "orderable": false, "targets": [0,1,2] }],
            "lengthChange": false,
            "searching": false,
            "ordering": false,
        });
    });
</script>