<?php
use Zend\Session\Container;
$sessao = new Container('usuario');
?>

<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix">  
                <div class="row panels">
                    <div class="col-md-12 pd-0" style="clear: both;">
                        <div class="box">                           
                            <div class="icon">
                                <div class="info" style="height: 500px;margin-top: 1px">
                                    <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12 pd-0" style="margin-bottom: 10px;width:100%;">         
                                        <div class="col-md-12 mt-3">
                                            <div class="jumbotron" style='background: #f5f5f5'>
                                                <h1 class="display-4">Olá, <?= $nome_usuario ?>!</h1>
                                                <p class="lead">Bem vindo ao Grupo de Estudos Edaci. Aqui você encontra uns negocio legal e faz um negocio legal pra nois.</p>
                                                <hr class="my-4">
                                                <p>Antes de continuar no sistema, precisamos que você responda um Questionário criado pelo Administrador do Grupo.<br> Este questionário leva em torno de 5 minutos para completar.</p>
                                                <br>
                                                <br>
                                                <br>
                                                <p class="lead">
                                                    <a class="btn btn-primary4 btn-lg" href="#" role="button">Responder Questionário &nbsp;<i class='fa fa-edit'></i></a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>                                                            	
                                </div>
                            </div>
                        </div> 
                    </div>
                </div>
                <div class="page-content"  style="margin-top: 20px">
                    <div id="footer">
                        <div class="row">
                            <div class="col-xs-12 col-md-12">
                                <div align="center" style="margin:10px;"><img src="/img/logo/unesp.png" alt="" class="unesp">&copy; 2019 - <?= date('Y') ?></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#relatorio').DataTable({
            "language": {
                "url": "js/datatable/pt-br.json"
            },
            "columnDefs": [ { "orderable": false, "targets": [0,1,2] }],
            "lengthChange": false,
            "searching": false
        });
    });
    
    function fotoPerfil(){
        
        $('#foto_perfil_brev').attr('src', '/arquivos/perfil/foto-perfil-<?= $sessao->cod_usuario ?>.jpg');
        
        $('#modalFoto').modal('show');
    }
    
    function escolherFoto(input) {
        
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            var ext = input.files[0].name.split('.').pop().toLowerCase();
            var isExt = ['png','jpg','jpeg'].indexOf(ext) > -1;
            
            if(!isExt){
                Swal.fire({
                    type    : 'info',
                    title   : 'Oops...',
                    html    : 'Escolha arquivos png, jpg ou jpeg.'
                });
                input.value = '';
                $('#foto_perfil_brev').attr('src', '/arquivos/perfil/foto-perfil-<?= $sessao->cod_usuario ?>.jpg');
                return false;
            }

            reader.onload = function (e) {
                $('#foto_perfil_brev')
                        .attr('src', e.target.result)
                        .width(250)
                        .height(250);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
    
    function salvar(){
        $('#fotoPerfilForm').submit();
        
    }
    
</script>