
<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix">  
                <!--div class="box-body ajust clearfix row pd-bottom-0">                       
                    <div class="row"> 
                        <div class="col-md-12 text-left">
                            <div class="margin-titulo">
                                <h1>Bem-vindo ao SISTARP!</h1>
                            </div>
                        </div>
                    </div>
                </div-->
                <div class="row"> 
                    <div class="main-box-body clearfix row pd-0 pd-arruma" style="display:none">
                        <div class="row">  
                            <hr>
                            <div class="col-md-12 col-xs-12 col-sm-12 back-banner">
                                <div class="direita">
                                    <a href="#" id="hideBanner" onclick="bannerToggle();">
                                        <i class="fa fa-window-minimize padding-icon" aria-hidden="true"></i>
                                    </a>    
                                    <a href="#" id="showBanner" onclick="bannerToggle();" style="display: none;">
                                        <i class="fa fa-plus padding-icon pd-plus" aria-hidden="true"></i>
                                    </a>    
                                </div>     
                            </div>     
                            <section class="section-white" id="bannerVo">
                                <div class="container container-new" style="padding-left: 0px; padding-right: 0px;">
                                    <div id="hinode-banners" class="carousel slide" data-ride="carousel">
                                        <ol class="carousel-indicators">                                        

                                            <li data-target="#hinode-banners" data-slide-to="0" class="active"></li>                                            

                                            <li data-target="#hinode-banners" data-slide-to="1" class=""></li>                                            

                                            <li data-target="#hinode-banners" data-slide-to="2" class=""></li>                                            

                                            <li data-target="#hinode-banners" data-slide-to="3" class=""></li>                                            

                                        </ol>
                                        <div class="carousel-inner">

                                            <div class="item active">                                                    
                                                <img src="./img/comunicado.png" class="img-slider" alt="" title="" />

                                            </div>                                       

                                            <div class="item ">                                                    
                                                <img src="./img/comunicado.png" class="img-slider" alt="" title="" />

                                            </div>                                       

                                            <div class="item ">                                                    
                                                <img src="./img/comunicado.png" class="img-slider" alt="" title="" />

                                            </div>                                       

                                            <div class="item ">                                                    
                                                <img src="./img/comunicado.png" class="img-slider" alt="" title="" />

                                            </div>                                                
                                        </div>
                                        <a class="left carousel-control" href="#hinode-banners" data-slide="prev">
                                            <span class="glyphicon glyphicon-chevron-left"></span>
                                        </a>
                                        <a class="right carousel-control" href="#hinode-banners" data-slide="next">
                                            <span class="glyphicon glyphicon-chevron-right"></span>
                                        </a>
                                    </div>
                                </div>
                            </section>
                        </div>   
                    </div>   
                </div>  
                <div class="row panels">
                    <div class="col-md-12 pd-0" style="clear: both;">
                        <div class="box">                           
                            <div class="icon">
                                <div class="image back-primary3"><i class="fa fa-exclamation-triangle"></i>&nbsp;<label class="title">Quadro de Avisos</label></div>
                                <div class="info" style="height: 350px;">
                                    <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12 pd-0" style="margin-bottom: 10px;width:100%">                    
                                        <div class="table-responsive" style="margin-top:10px;width:100%">
                                            <table id="tabela" class="table table-striped table-bordered dataTable-primary" style="width:100%">
                                                <thead>
                                                    <tr>
                                                        <th>Assunto</th>
                                                        <th>Descrição</th>
                                                        <th>Recebido em</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr style="text-align: left">
                                                        <td>Processo Seletivo</td>
                                                        <td>O processo seletivo de 2019 foi aberto. Inscreva-se.</td>
                                                        <td>20/05/2019 12:00:00</td>
                                                        <td style="text-align: center"><i class="fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Atualização de suas informações</td>
                                                        <td>Por favor, mantenha sempre suas informações atualizadas.</td>
                                                        <td>01/05/2019 13:00:00</td>
                                                        <td style="text-align: center"><i class="fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Oportunidade de Estágio</td>
                                                        <td>Uma nova oportunidade de estágio surgiu em sua região.</td>
                                                        <td>23/04/2019 09:00:00</td>
                                                        <td style="text-align: center"><i class="fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Trabalho para Correção</td>
                                                        <td>Cláudio te enviou um Trabalho para Correção.</td>
                                                        <td>10/04/2019 08:00:00</td>
                                                        <td style="text-align: center"><i class="fa fa-times"></i></td>
                                                    </tr>
                                                    <tr style="text-align: left">
                                                        <td>Oportunidade de Estágio</td>
                                                        <td>Uma nova oportunidade de estágio surgiu em sua região.</td>
                                                        <td>05/04/2019 17:00:00</td>
                                                        <td style="text-align: center"><i class="fa fa-times"></i></td>
                                                    </tr>
                                                </tbody>
                                            </table>   
                                        </div>
                                    </div>                                                            	
                                </div>
                            </div>
                        </div> 
                    </div>
                    <div class="col-xs-12 col-sm-12 col-lg-6 col-md-6 pd-0" style="margin-top: 20px">
                        <div class="box">                           
                            <div class="icon">
                                <div class="image back-primary3"><i class="fa fa-play-circle"></i>&nbsp;<label class="title">Vídeo de instrução</label></div>
                                <div class="info" style="min-height:450px">
                                    <div class="panels box-initial-header">
                                        <div class="row">
                                            <div class="col-sm-12 col-md-12 col-xs-12">
                                                <img width="100%" height="315" src="https://www.videoflyer.com.br/wordpress/wp-content/uploads/2018/03/Video-Explicativo.jpg"> 
                                                <!--iframe width="100%" height="315" src="https://www.youtube.com/embed/CmFqnUNuZG4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe-->
                                            </div>                                                                                                
                                        </div>  
                                    </div>    
                                </div>
                            </div>
                        </div> 
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 pd-0" style="margin-top: 20px">
                        <div class="box">                           
                            <div class="icon">
                                <div class="image back-primary3"><i class="fa fa-question-circle"></i>&nbsp;<label class="title">Sobre o EDACI</label></div>
                                <div class="info" style="min-height:450px">
                                    <div class="panels box-initial-header; back-ground-color:white">
                                        <div class="col-md-12 table-responsive" style="margin-top:50px">
                                            <b class="text-left" style="color:#333;">O Grupo de Pesquisa Educação e Acidentes (EDACI) da UNESP Marília, <br>tem como função produzir estudos e intervenções educativas<br> para prevenção de acidentes e promoção da segurança.<br>Faça o download do arquivo abaixo para mais informações:</p>
                                                <a href="/" style="width:90%; margin-top: 10px;" class="btn btn-primary3 btn-pad" id="botaoPrincipal">
                                                    <strong><span class="hidden-xs showopacity fa fa-download icon-ajuste"></span>Download do Arquivo</strong></a>   
                                        </div> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="page-content"  style="margin-top: 20px">
                    <div id="footer">
                        <div class="row">
                            <div class="col-xs-12 col-md-12">
                                <div align="center" style="margin:10px;"><img src="/img/logo/unesp.png" alt="" class="unesp">&copy; 2019 - <?= date('Y') ?></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#tabela').DataTable({
            "language": {
                "url": "js/datatable/pt-br.json"
            },
            "columnDefs": [ { "orderable": false, "targets": [0,1,3] }],
            "lengthChange": false,
            "searching": false
        });
    });
</script>