<div class="row box-home" align="center" style="height:100%">
    <div class="col-md-12 col-xs-12">  
        <div class="main-box clearfix print min-branco rodapeindex">
            <div class="main-box-body clearfix mt">  
                <div class="box-body ajust clearfix row pd-bottom-0">                       
                    <div class="row"> 
                        <div class="col-md-12 text-left">
                            <div class="margin-titulo">
                                <h1>Bem-vindo ao SISTARP!</h1>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="main-box-body clearfix row pd-0 pd-arruma" style="display:none">
                    <div class="row">  
                        <hr>
                        <div class="col-md-12 col-xs-12 col-sm-12 back-banner">
                            <div class="direita">
                                <a href="#" id="hideBanner" onclick="bannerToggle();">
                                    <i class="fa fa-window-minimize padding-icon" aria-hidden="true"></i>
                                </a>    
                                <a href="#" id="showBanner" onclick="bannerToggle();" style="display: none;">
                                    <i class="fa fa-plus padding-icon pd-plus" aria-hidden="true"></i>
                                </a>    
                            </div>    
                        </div>     
                        <section class="section-white" id="bannerVo">
                            <div class="container container-new" style="padding-left: 0px; padding-right: 0px;">
                                <div id="hinode-banners" class="carousel slide" data-ride="carousel">
                                    <ol class="carousel-indicators">                                        

                                        <li data-target="#hinode-banners" data-slide-to="0" class="active"></li>                                            

                                        <li data-target="#hinode-banners" data-slide-to="1" class=""></li>                                            

                                        <li data-target="#hinode-banners" data-slide-to="2" class=""></li>                                            

                                        <li data-target="#hinode-banners" data-slide-to="3" class=""></li>                                            

                                    </ol>
                                    <div class="carousel-inner">

                                        <div class="item active">                                                    
                                            <img src="./img/comunicado.png" class="img-slider" alt="" title="" />

                                        </div>                                       

                                        <div class="item ">                                                    
                                            <img src="./img/comunicado.png" class="img-slider" alt="" title="" />

                                        </div>                                       

                                        <div class="item ">                                                    
                                            <img src="./img/comunicado.png" class="img-slider" alt="" title="" />

                                        </div>                                       

                                        <div class="item ">                                                    
                                            <img src="./img/comunicado.png" class="img-slider" alt="" title="" />

                                        </div>                                                
                                    </div>
                                    <a class="left carousel-control" href="#hinode-banners" data-slide="prev">
                                        <span class="glyphicon glyphicon-chevron-left"></span>
                                    </a>
                                    <a class="right carousel-control" href="#hinode-banners" data-slide="next">
                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                    </a>
                                </div>
                            </div>
                        </section>
                    </div>   
                </div>    
                <div class="container pd-0">
                    <div class="row" style="margin-top: -60px;">
                        <div class="col-md-12 pd-0" >
                            <div class="box">                           
                                <div class="icon">
                                    <div class="image back-primary3"><i class="fa fa-exclamation-triangle"></i></div>
                                    <div class="info" style="height:250px;">
                                        <h3 class="title">Quadro de Avisos</h3>
                                        <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12 pd-0">                    
                                            <div class="new-color-1 border-new-color-1"> 
                                                <b class="cinza-escuro">&nbsp;</b>
                                            </div> 
                                            <div class="table-responsive">
                                                <table class="table table-striped table-bordered table-hover">    
                                                    <tr class="font-min">
                                                        <td align="center" width="30%">
                                                            <span class="fa fa-exclamation-circle icon-ajuste falert"></span><b>Aviso 1</b>
                                                        </td>
                                                        <td align="left">
                                                            <b>&nbsp;&nbsp;To te avisano</b>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td align="center">
                                                            <span class="fa fa-exclamation-circle icon-ajuste falert"></span><b>Aviso 2</b>
                                                        </td>   
                                                        <td align="left">
                                                            <b>&nbsp;&nbsp;To te avisano ein</b>
                                                        </td>
                                                    </tr> 
                                                    <tr>
                                                        <td align="center">
                                                            <span class="fa fa-exclamation-circle icon-ajuste falert"></span><b>Aviso 3</b>
                                                        </td>  
                                                        <td align="left">
                                                            <b>&nbsp;&nbsp;Oia to te avisano</b>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td align="center">
                                                            <span class="fa fa-exclamation-circle icon-ajuste falert"></span><b>Aviso 4</b>
                                                        </td>  
                                                        <td align="left">
                                                            <b>&nbsp;&nbsp;Quando eu te avisa vo ti bate tanto, ti bate tanto </b>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td align="center">
                                                            <span class="fa fa-exclamation-circle icon-ajuste falert"></span><b>Aviso 5</b>
                                                        </td>  
                                                        <td align="left">
                                                            <b>&nbsp;&nbsp;Não vo te avisa mais ragabun </b>
                                                        </td>
                                                    </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>                                                            	
                                    </div>
                                </div>
                                <div class="space"></div>
                            </div> 
                        </div>
                    </div>        
                    <div class="col-xs-12 col-sm-12 col-lg-6 col-md-6 pdr-0">
                        <div class="box">                           
                            <div class="icon">
                                <div class="image back-primary3"><i class="fa fa-play-circle"></i></div>
                                <div class="info" style="min-height:450px">
                                    <h3 class="title">Vídeo de instruções</h3>
                                    <div class="box-initial-header">
                                        <div class="row">
                                            <div class="col-sm-12 col-md-12 col-xs-12">
                                                <iframe width="100%" height="315" src="https://www.youtube.com/embed/CmFqnUNuZG4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                            </div>                                                                                                
                                        </div>  
                                    </div>    
                                </div>
                            </div>
                            <div class="space"></div>
                        </div> 
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 pd-0">
                        <div class="box">                           
                            <div class="icon">
                                <div class="image back-primary3"><i class="fa fa-question-circle"></i></div>
                                <div class="info" style="min-height:450px">
                                    <h3 class="title">Sobre o EDACI</h3>
                                    <div class="box-initial-header; back-ground-color:white">
                                        <div class="col-md-12 table-responsive" style="margin-top:50px">
                                            <b class="text-left" style="color:#333;">O Grupo de Pesquisa Educação e Acidentes (EDACI) da UNESP Marília, <br>tem como função produzir estudos e intervenções educativas<br> para prevenção de acidentes e promoção da segurança.<br>Faça o download do arquivo abaixo para mais informações:</p>
                                                <a href="/" style="width:90%; margin-top: 10px;" class="btn btn-primary3 btn-pad" id="botaoPrincipal">
                                                    <strong><span class="hidden-xs showopacity fa fa-download icon-ajuste"></span>Download do Arquivo</strong></a>   
                                        </div> 
                                    </div>
                                </div>
                            </div>
                            <div class="space"></div>
                        </div>
                    </div>
                </div>
                <div class="page-content">
                    <div id="footer">
                        <div class="row">
                            <div class="col-xs-12 col-md-12">
                                <div align="center" style="margin:10px;"><img src="/img/logo/unesp.png" alt="" class="unesp">&copy; 2019 - <?= date('Y') ?></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>