<div class="col-md-6">
	<div class="panel panel-default">
		<div class="panel-heading bgedit" style="background-color:#629bad">
			<h4 class="ftedit">QUESTIONÁRIO INICIAL</h4>
		</div>
		<div class="panel-body">
			<div class="col-xs-12 col-sm-12 col-md-12">
				<div class="form-group text-left">                                                                           
					<label>1) Assinale se apresentar uma ou mais condições apresentadas abaixo<b style="color: red;">*</b>:</label>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12">
					<div class="form-group text-left"> 
								<div class="col-md-4">
									<label class="radio-inline">
										<input type="checkbox" class="chkCondicao" name="optCondicao">&nbsp;SIM
									</label>
								</div>
								<div class="col-md-4">
									<label class="radio-inline">
										<input type="checkbox" class="chkCondicao" name="optCondicao">&nbsp;SIM
									</label>
								</div>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-12" style="margin-top:20px;">
				<div class="form-group text-left">                                                                           
					<label>2) Você passou por alguma cirurgia recente (últimos 6 meses) ?> <b style="color: red;">*</b>:</label>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12">
					<div class="form-group"> 
						<div class="col-md-4 text-left">
							<label class="radio-inline">
								<input type="radio" class="resposta2" value="1" name="resposta2">&nbsp;Sim
							</label>
							<label class="radio-inline">
								<input type="radio" class="resposta2" value="0" name="resposta2">&nbsp;Não
							</label>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-12" style="margin-top:20px;">
				<div class="form-group text-left">                                                                           
					<label>3) Você faz uso de medicação contínua e controlada ? <b style="color: red;">*</b>:</label>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12">
					<div class="form-group"> 
						<div class="col-md-4 text-left">
							<label class="radio-inline">
								<input type="radio" class="resposta3" value="1" name="resposta3">&nbsp;Sim
							</label>
							<label class="radio-inline">
								<input type="radio" class="resposta3" value="0" name="resposta3">&nbsp;Não
							</label>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-12" style="margin-top:20px;">
				<div class="form-group text-left">                                                                           
					<label>4)Você apresenta alergia ou intolerância a algum alimento e/ou princípio ativo?<b style="color: red;">*</b>:</label>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12">
					<div class="form-group"> 
						<div class="col-md-4 text-left">
							<label class="radio-inline">
								<input type="radio" class="resposta4" value="1" name="resposta4">&nbsp;Sim
							</label>
							<label class="radio-inline">
								<input type="radio" class="resposta4" value="0" name="resposta4">&nbsp;Não
							</label>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-12 text-center">
				<button class="btn btn-primary3">Enviar</button>
			</div>
		</div>
	</div>
	</div>